"use client";

import { CheckCircle2, Link2, ShieldCheck } from "lucide-react";
type Action=(message:string)=>void;
const specialists=[
  {name:"Provider & Campaign Operations",duty:"Monitors approved providers, imports campaign drafts, validates targeting, caps and dates, and prepares publish, pause or resume requests."},
  {name:"Postback, Reward & Revenue Reconciliation",duty:"Matches signed callbacks to task attempts, identifies missing or duplicate events, and prepares reward and revenue exceptions for human review."},
];
const tone=(v:string)=>v==="Critical"||v==="Blocked"?"bg-rose-50 text-rose-700":v==="Review"||v==="Pending"||v==="Degraded"?"bg-amber-50 text-amber-700":v==="Ready"||v==="Active"||v==="Matched"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600";
function List({title,subtitle,items,action}:{title:string;subtitle:string;items:string[][];action?:Action}){return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name,detail,state])=><article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><CheckCircle2 size={16}/></span><div className="min-w-0"><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${tone(state)}`}>{state}</span>{action&&<button onClick={()=>action(`${name} opened for supervised ads review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>}
export function AdsOperationsOverview({onOpen}:{onOpen:(tab:string)=>void}){return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Approved providers","4","1 needs review"],["Active campaigns","38","3 near cap"],["Callbacks today","12,480","99.4% matched"],["Revenue exceptions","7","Human review"]].map(([label,value,note])=><article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><div><h2 className="font-bold">Ads operations team</h2><p className="mt-1 text-xs text-slate-500">Separated campaign and reconciliation duties.</p></div><button onClick={()=>onOpen("Subagents")} className="ml-auto text-xs font-bold text-violet-700">Manage team →</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{specialists.map((item,index)=><article key={item.name} className="rounded-2xl border p-5"><span className="text-[9px] font-bold text-violet-600">SPECIALIST 0{index+1}</span><h3 className="mt-2 text-sm font-bold">{item.name}</h3><p className="mt-3 text-xs leading-5 text-slate-500">{item.duty}</p></article>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human decision boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">Agents monitor, validate, match and recommend. Provider activation, credentials, campaign publishing, budget or reward changes, wallet corrections and reconciliation exceptions require authorized human approval.</p></article></section></div>}
export function AdsOperationsSubagents({onInstruct}:{onInstruct:(name:string)=>void}){return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Ads Operations subagents</h2><p className="mt-1 text-xs text-slate-500">Direct instructions remain below company policy, provider contracts and approval rules.</p></div><div className="grid gap-4 p-5 lg:grid-cols-2">{specialists.map((item,index)=><article key={item.name} className="rounded-2xl border p-5"><p className="text-[9px] font-bold text-violet-600">SPECIALIST 0{index+1}</p><h3 className="mt-1 text-sm font-bold">{item.name}</h3><p className="mt-3 text-xs leading-5 text-slate-500">{item.duty}</p><button onClick={()=>onInstruct(item.name)} className="mt-4 h-9 rounded-xl border border-violet-200 px-3 text-[10px] font-bold text-violet-700">Chat & instruct</button></article>)}</div></section>}
export const AdsProviders=({action}:{action:Action})=><List title="Ad Providers" subtitle="Provider readiness, signed callback health and approved gateway status. Secrets stay server-side." action={action} items={[["Rewarded video network","Gateway ready · signed callbacks","Ready"],["Display ads provider","Commercial approval pending","Pending"],["Video provider B","Callback rejection rate elevated","Degraded"],["Provider credentials","Encrypted server reference only","Protected"]]}/>;
export const AdsCampaigns=({action}:{action:Action})=><List title="Campaigns" subtitle="Campaign drafts, targeting, caps, dates and protected publishing controls." action={action} items={[["Watch & Earn · Summer video","India · Android/iOS · 72% budget","Active"],["Rewarded display · August","Draft validation complete","Ready"],["Video campaign · Tier 1","Daily conversion cap near limit","Review"],["Expired provider campaign","End time reached automatically","Paused"]]}/>;
export const AdsRewardTracking=({action}:{action:Action})=><List title="Reward Tracking" subtitle="Signed callbacks matched to task attempts and immutable reward evidence." action={action} items={[["12,401 callbacks matched","Verified today","Matched"],["48 callbacks awaiting attempt","Provider reference incomplete","Review"],["19 duplicate callbacks","Idempotency protection applied","Blocked"],["12 paid-reward reversals","Manual decision required","Critical"]]}/>;
export const AdsRevenueReconciliation=({action}:{action:Action})=><List title="Revenue Reconciliation" subtitle="Provider revenue, campaign budget entries and user reward evidence compared without moving money." action={action} items={[["Daily provider statement","Revenue and reward totals matched","Matched"],["Campaign 4821 variance","₹2,840 difference","Review"],["Missing provider statement","Due 18:00 IST","Pending"],["Wallet correction","Finance approval required","Protected"]]}/>;
export const AdsTasks=()=> <List title="Ads Operations Tasks" subtitle="Traceable assignments owned by the main agent or a specialist." items={[["Validate new campaign feed","Provider & Campaign Operations · due now","Review"],["Investigate callback variance","Postback & Reconciliation · 18 min","Critical"],["Prepare provider health summary","Ads Operations Agent · 18:00 IST","Ready"]]}/>;
export const AdsReports=()=> <List title="Ads Operations Reports" subtitle="Daily and weekly summaries prepared for Chief Operations." items={[["Daily campaign health","18:00 IST","Active"],["Reward exception report","Every 4 hours","Ready"],["Weekly provider revenue","Monday 09:00 IST","Ready"]]}/>;
export const AdsApprovals=({action}:{action:Action})=><List title="Ads Operations Approvals" subtitle="Agents prepare evidence; an authorized human decides." action={action} items={[["Activate display provider","Credentials and signed test required","Pending"],["Publish August campaign","Targeting and economics attached","Pending"],["Increase campaign budget","Owner approval required","Protected"],["Paid reward reversal","Finance and risk review required","Critical"]]}/>;
export const AdsAutomations=({action}:{action:Action})=><List title="Ads Operations Automations" subtitle="Monitoring and reporting only; no autonomous provider activation, budget change or wallet correction." action={action} items={[["Provider health scan","Every 5 minutes","Active"],["Campaign cap monitor","Every 10 minutes","Active"],["Reward mismatch detector","Every 15 minutes","Active"],["Daily operations brief","18:00 IST","Ready"]]}/>;
export const AdsActivityHistory=()=> <List title="Ads Operations Activity History" subtitle="Read-only timeline of provider checks, campaign reviews, callback matches and human decisions." items={[["Campaign cap warning created","Campaign 4821 · system","3 min ago"],["Callback variance escalated","Specialist 02 · agent","11 min ago"],["Provider health checked","Video provider B","18 min ago"],["Campaign publish approved","Operations owner","41 min ago"]]}/>;
export const AdsConnections=({action}:{action:Action})=><div className="grid gap-5 lg:grid-cols-2"><List title="API Connections" subtitle="Approved server-to-server gateways and signed callback endpoints." action={action} items={[["Campaign feed API","Read-only import scope","Ready"],["Signed postback endpoint","HMAC-SHA256 · replay protected","Active"],["Provider reporting API","Revenue statement scope","Review"],["Credential vault","No browser or instruction access","Protected"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><Link2 size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">What you provide</h2><p className="mt-2 text-xs leading-5 text-amber-900">Provider name, documentation URL, campaign-feed endpoint, reporting endpoint, callback specification, allowed IPs and server credential. Credentials go to the encrypted vault, never agent chat.</p></article></div>;
export const AdsSettings=()=> <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Monitoring targets and escalation thresholds." items={[["Callback health check","Every 5 minutes","Active"],["Mismatch escalation","After 15 minutes","Active"],["Campaign cap warning","At 85%","Active"],["Daily report","18:00 IST","Ready"]]}/><List title="Safety & Permissions" subtitle="Protected actions agents cannot execute alone." items={[["Activate provider","Owner + AAL2","Protected"],["Publish or change campaign","Owner approval","Protected"],["Change budget or reward","Owner approval","Blocked"],["Modify wallet or ledger","Finance workflow only","Blocked"],["Override fraud controls","Never permitted","Blocked"]]}/></div>;
