"use client";

import { CheckCircle2, KeyRound, ShieldCheck } from "lucide-react";

type Action = (message: string) => void;
const specialists = [
  ["Provider Connection", "Prepares provider onboarding, API/feed mappings, callback tests and credential-vault requests."],
  ["Product Feed", "Imports approved product feeds and checks freshness, price, stock and category mappings."],
  ["Catalog Quality", "Finds duplicates, broken images, missing terms, unsafe content and stale products."],
  ["Deal Ranking", "Recommends transparent deal order using value, availability, quality and performance signals."],
  ["Tracking Link", "Creates signed click-attribution requests and validates approved destinations and parameters."],
  ["Commission Reconciliation", "Matches provider conversions, commissions and cashback evidence and raises exceptions."],
];
const badge = (state: string) => state === "Critical" || state === "Blocked" ? "bg-rose-50 text-rose-700" : state === "Review" || state === "Pending" || state === "Degraded" ? "bg-amber-50 text-amber-700" : state === "Ready" || state === "Active" || state === "Matched" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600";
function List({ title, subtitle, items, action }: { title: string; subtitle: string; items: string[][]; action?: Action }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name, detail, state]) => <article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><CheckCircle2 size={16}/></span><div className="min-w-0"><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${badge(state)}`}>{state}</span>{action && <button onClick={() => action(`${name} opened for supervised affiliate review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>; }

export function AffiliateShopOverview({ onOpen }: { onOpen: (tab: string) => void }) { return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Approved providers", "8", "1 needs review"], ["Catalog products", "48,216", "96.4% healthy"], ["Tracked clicks", "31,840", "Today"], ["Commission exceptions", "17", "Human review"]].map(([label, value, note]) => <article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><div><h2 className="font-bold">Affiliate specialist team</h2><p className="mt-1 text-xs text-slate-500">Six focused subagents with separated responsibilities.</p></div><button onClick={() => onOpen("Subagents")} className="ml-auto text-xs font-bold text-violet-700">Manage team →</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{specialists.map(([name, duty], index) => <article key={name} className="rounded-2xl border p-4"><span className="text-[9px] font-bold text-violet-600">SPECIALIST 0{index + 1}</span><h3 className="mt-2 text-sm font-bold">{name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{duty}</p></article>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human decision boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">Agents may import, validate, rank, monitor and recommend. Provider activation, catalog or deal publishing, commission or cashback changes, tracking-domain changes and wallet credits require an authorized human.</p></article></section></div>; }
export const AffiliateProviders = ({ action }: { action: Action }) => <List title="Providers" subtitle="Affiliate networks and merchant connections. Activation always requires approval." action={action} items={[["Partner network A", "API and callback mapping verified", "Ready"], ["Retail marketplace B", "Product feed active", "Active"], ["Travel partner C", "Callback latency elevated", "Degraded"], ["New provider request", "Contract and security review", "Pending"]]}/>;
export const ProductFeeds = ({ action }: { action: Action }) => <List title="Product Feeds" subtitle="Feed freshness, schema mappings, price, stock and image validation." action={action} items={[["Marketplace product feed", "Updated 12 minutes ago", "Active"], ["Fashion merchant feed", "1.8% products need review", "Review"], ["Travel deals feed", "Updated hourly", "Ready"], ["Electronics delta feed", "Schema mapping incomplete", "Pending"]]}/>;
export const ProductCatalog = ({ action }: { action: Action }) => <List title="Product Catalog" subtitle="Quality-controlled product drafts; nothing publishes automatically." action={action} items={[["46,480 approved products", "Price and stock checks passed", "Active"], ["824 duplicate candidates", "Merge recommendation prepared", "Review"], ["612 broken images", "Provider refresh requested", "Degraded"], ["300 restricted listings", "Policy control applied", "Blocked"]]}/>;
export const StoresDeals = ({ action }: { action: Action }) => <List title="Stores & Deals" subtitle="Storefront readiness and explainable deal-ranking recommendations." action={action} items={[["Summer savings collection", "Ranking review complete", "Ready"], ["Top cashback stores", "Cashback terms verified", "Active"], ["Flash deal group", "Expiry check required", "Review"], ["Unverified discount claim", "Publishing prevented", "Blocked"]]}/>;
export const ClickTracking = ({ action }: { action: Action }) => <List title="Click Tracking" subtitle="Signed attribution links, approved destinations and replay-resistant evidence." action={action} items={[["31,840 signed clicks", "Today · approved destinations", "Active"], ["99.7% redirect success", "Last 24 hours", "Ready"], ["43 expired tokens", "Rejected safely", "Blocked"], ["Destination domain change", "Owner approval required", "Pending"]]}/>;
export const AffiliateCommissions = ({ action }: { action: Action }) => <List title="Commissions" subtitle="Provider conversions matched to click, order, commission and cashback evidence." action={action} items={[["2,418 matched conversions", "Current settlement window", "Matched"], ["17 amount mismatches", "Evidence prepared", "Critical"], ["29 pending return windows", "No credit action yet", "Pending"], ["4 reversal requests", "Finance and risk approval", "Review"]]}/>;
export const AffiliateTasks = () => <List title="Affiliate Tasks" subtitle="Traceable assignments for the main agent and six specialists." items={[["Review new provider mapping", "Provider Connection · due now", "Review"], ["Resolve feed duplicates", "Catalog Quality · 42 min", "Active"], ["Prepare commission exceptions", "Commission Reconciliation · 18:00 IST", "Ready"]]}/>;
export const AffiliateReports = () => <List title="Affiliate Reports" subtitle="Operational summaries delivered to Chief Operations." items={[["Daily catalog health", "18:00 IST", "Active"], ["Click and conversion quality", "Every 4 hours", "Ready"], ["Weekly provider performance", "Monday 09:00 IST", "Ready"], ["Commission exceptions", "Daily", "Review"]]}/>;
export const AffiliateApprovals = ({ action }: { action: Action }) => <List title="Affiliate Approvals" subtitle="Agents assemble evidence; authorized humans make protected decisions." action={action} items={[["Activate new provider", "Security and contract evidence attached", "Pending"], ["Publish deal collection", "Quality review complete", "Pending"], ["Change cashback rate", "Owner and finance approval", "Protected"], ["Commission exception", "Provider evidence mismatch", "Critical"]]}/>;
export const AffiliateAutomations = ({ action }: { action: Action }) => <List title="Affiliate Automations" subtitle="Monitoring and drafts only; no autonomous publishing, commission change or wallet credit." action={action} items={[["Feed freshness monitor", "Every 15 minutes", "Active"], ["Catalog quality scan", "Every hour", "Active"], ["Click mismatch detector", "Every 10 minutes", "Active"], ["Daily affiliate brief", "18:00 IST", "Ready"]]}/>;
export const AffiliateActivity = () => <List title="Affiliate Activity History" subtitle="Read-only provider, feed, catalog, click, commission and approval evidence." items={[["Commission exception escalated", "Conversion evidence preserved", "3 min ago"], ["Product feed validated", "Product Feed specialist", "14 min ago"], ["Unsafe destination blocked", "Tracking Link specialist", "25 min ago"], ["Deal publish approved", "Operations owner", "51 min ago"]]}/>;
export const AffiliateConnections = ({ action }: { action: Action }) => <div className="grid gap-5 lg:grid-cols-2"><List title="API Connections" subtitle="Provider feeds, reporting APIs and signed callbacks; secrets remain server-side." action={action} items={[["Product feed API", "Read-only catalog import", "Ready"], ["Affiliate reporting API", "Commission reconciliation", "Active"], ["Signed conversion callback", "HMAC and replay protection", "Active"], ["Credential vault", "No agent-chat access", "Protected"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><KeyRound size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">What you provide</h2><p className="mt-2 text-xs leading-5 text-amber-900">Provider name, documentation URL, API or feed endpoint, authentication method, merchant mapping, tracking parameters, callback specification and allowed domains or IPs. Credentials are entered into the encrypted server vault—never into agent chat.</p></article></div>;
export const AffiliateSettings = () => <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Monitoring schedules and escalation thresholds." items={[["Feed freshness check", "Every 15 minutes", "Active"], ["Broken-link alert", "After 3 failures", "Active"], ["Commission mismatch alert", "Any amount difference", "Active"], ["Daily report", "18:00 IST", "Ready"]]}/><List title="Safety & Permissions" subtitle="Protected actions agents cannot execute alone." items={[["Activate provider", "Owner + AAL2", "Protected"], ["Publish catalog or deal", "Owner approval", "Protected"], ["Change tracking domain", "Owner approval", "Blocked"], ["Adjust commission or cashback", "Finance workflow", "Blocked"], ["Credit wallet", "Wallet ledger workflow only", "Blocked"]]}/></div>;
