"use client";
import { useState } from "react";
import { Bot, CirclePause, Play, ShieldCheck } from "lucide-react";
import { runtimeProviders } from "../../lib/agents/runtime/providers";
import type { ApprovalRisk, RuntimeProvider, RuntimeResult } from "../../lib/agents/runtime/types";

const departments = ["Support Team Lead Agent", "Fraud & Risk Agent", "Payments & Wallet Agent", "Compliance, KYC & Finance Agent", "Ads Operations Agent", "Offerwall & Tasks Agent", "Affiliate & Shop Agent", "Content Manager Agent", "Creative Production Agent", "Social Media Agent", "Performance Marketing Agent", "Data & Business Analyst Agent", "Technical Operations Agent"];

export function AgentRuntimeControl() {
  const [objective,setObjective]=useState("Review unresolved department escalations and prepare a CEO briefing.");
  const [mainAgent,setMainAgent]=useState(departments[0]);
  const [provider,setProvider]=useState<RuntimeProvider>("openai");
  const [approvalRisk,setApprovalRisk]=useState<ApprovalRisk>("ceo");
  const [result,setResult]=useState<RuntimeResult|null>(null);
  const [error,setError]=useState(""); const [running,setRunning]=useState(false);
  async function run(){setRunning(true);setError("");setResult(null);try{const response=await fetch("/api/admin/agents/runtime/simulate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({objective,mainAgent,provider,modelAlias:runtimeProviders[provider].defaultModelAlias,tokenBudget:4000,timeoutMs:30000,maxRetries:1,approvalRisk})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Simulation failed.");setResult(body);}catch(cause){setError(cause instanceof Error?cause.message:"Simulation failed.");}finally{setRunning(false);}}
  return <div className="space-y-5">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Runtime mode","Simulation only"],["Live AI calls","Disabled"],["Emergency pause","Ready"],["Provider adapters","4 available"]].map(([label,value])=><article key={label} className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-lg font-bold">{value}</p></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3"><Bot className="text-violet-600"/><div><h2 className="font-bold">Simulate an agent run</h2><p className="text-xs text-slate-500">Preview routing, approvals, tokens and cost without contacting an AI provider.</p></div></div>
      <label className="mt-5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Objective<textarea value={objective} onChange={e=>setObjective(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border p-3 text-xs normal-case tracking-normal"/></label>
      <label className="mt-3 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Department agent<select value={mainAgent} onChange={e=>setMainAgent(e.target.value)} className="mt-2 h-10 w-full rounded-xl border bg-white px-3 text-xs normal-case tracking-normal">{departments.map(item=><option key={item}>{item}</option>)}</select></label>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">AI provider<select value={provider} onChange={e=>setProvider(e.target.value as RuntimeProvider)} className="mt-2 h-10 w-full rounded-xl border bg-white px-3 text-xs normal-case tracking-normal">{Object.values(runtimeProviders).map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Approval gate<select value={approvalRisk} onChange={e=>setApprovalRisk(e.target.value as ApprovalRisk)} className="mt-2 h-10 w-full rounded-xl border bg-white px-3 text-xs normal-case tracking-normal"><option value="none">No protected action</option><option value="department">Department owner</option><option value="ceo">CEO approval</option></select></label></div>
      <button disabled={running||!objective.trim()} onClick={()=>void run()} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-violet-600 text-xs font-bold text-white disabled:opacity-40"><Play size={15}/>{running?"Simulating…":"Run safe simulation"}</button>{error&&<p role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}</article>
      <div className="space-y-5"><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><CirclePause className="text-amber-700"/><h2 className="mt-3 font-bold">Hard safety boundary</h2><p className="mt-2 text-xs leading-5 text-amber-900">No live AI calls, token spending, company-data changes or approval bypasses. Provider keys remain server-side.</p></article>{!result?<article className="rounded-2xl border border-dashed bg-white p-10 text-center"><ShieldCheck className="mx-auto text-slate-300"/><h3 className="mt-3 text-sm font-bold">No simulation yet</h3></article>:<article className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">Simulation result</h2><p className="mt-1 text-xs text-slate-500">{result.summary}</p><div className="mt-4 grid grid-cols-3 gap-3">{[["Input",result.estimatedInputTokens+" tokens"],["Output",result.estimatedOutputTokens+" tokens"],["Estimate","$"+result.estimatedCostUsd.toFixed(4)]].map(([a,b])=><div key={a} className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] text-slate-400">{a}</p><b className="text-xs">{b}</b></div>)}</div></div><div className="divide-y">{result.traces.map(trace=><div key={trace.order} className="flex gap-3 p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-violet-50 text-[9px] font-bold text-violet-700">{String(trace.order).padStart(2,"0")}</span><div><b className="text-xs capitalize">{trace.stage} · {trace.status}</b><p className="mt-1 text-[10px] leading-4 text-slate-500">{trace.detail}</p></div></div>)}</div></article>}</div></section>
  </div>;
}
