"use client";

import { CalendarDays, CheckCircle2, ShieldCheck } from "lucide-react";

type Action = (message: string) => void;
const tone = (state: string) => state === "Blocked" || state === "Critical" ? "bg-rose-50 text-rose-700" : state === "Review" || state === "Pending" ? "bg-amber-50 text-amber-700" : state === "Ready" || state === "Scheduled" || state === "Approved" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600";
function List({ title, subtitle, items, action }: { title: string; subtitle: string; items: string[][]; action?: Action }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name, detail, state]) => <article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><CheckCircle2 size={16}/></span><div className="min-w-0"><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${tone(state)}`}>{state}</span>{action && <button onClick={() => action(`${name} opened for supervised content review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>; }

export function ContentManagerOverview({ onOpen }: { onOpen: (tab: string) => void }) { return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Planned items", "42", "Next 30 days"], ["Drafts in progress", "16", "Across campaigns"], ["Awaiting approval", "7", "Human decision"], ["Published by humans", "28", "This month"]].map(([label, value, note]) => <article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><div><h2 className="font-bold">Content operations</h2><p className="mt-1 text-xs text-slate-500">One accountable manager prepares content work and coordinates specialist departments.</p></div><button onClick={() => onOpen("Content Calendar")} className="ml-auto text-xs font-bold text-violet-700">Open calendar →</button></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Plan", "Turn approved business priorities into a dated content calendar."], ["Prepare", "Create briefs and campaign-copy drafts using approved sources."], ["Review", "Check brand, claims, links, audience and compliance before approval."]].map(([name, duty], index) => <article key={name} className="rounded-2xl border p-4"><span className="text-[9px] font-bold text-violet-600">STAGE 0{index + 1}</span><h3 className="mt-2 text-sm font-bold">{name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{duty}</p></article>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human publishing boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">The agent may research approved sources, plan, draft, review and recommend. It cannot publish, make regulated claims, change brand policy, approve its own work or use an unapproved source.</p></article></section></div>; }
export const ContentCalendar = ({ action }: { action: Action }) => <List title="Content Calendar" subtitle="Planned content by channel, owner, campaign, date and approval state." action={action} items={[["Weekly rewards guide", "Blog · 24 Aug · owner review", "Review"], ["Cashback education series", "App and email · 26 Aug", "Scheduled"], ["Safety awareness update", "Help centre · compliance check", "Pending"], ["Festival campaign", "Multi-channel · brief ready", "Ready"]]}/>;
export const ContentBriefs = ({ action }: { action: Action }) => <List title="Content Briefs" subtitle="Objectives, audience, facts, sources, channel, CTA and required reviewers." action={action} items={[["How cashback tracking works", "Audience and verified facts complete", "Ready"], ["New survey campaign", "Reward terms need confirmation", "Review"], ["Merchant launch", "Approved product source attached", "Ready"], ["Financial advice draft", "Outside permitted content scope", "Blocked"]]}/>;
export const CampaignCopy = ({ action }: { action: Action }) => <List title="Campaign Copy" subtitle="Versioned copy drafts with channel limits and brand checks." action={action} items={[["Welcome email refresh", "Version 3 · brand check passed", "Review"], ["Push notification set", "8 variants · character limits passed", "Ready"], ["Homepage reward message", "Offer terms attached", "Pending"], ["Unverified earnings claim", "Claims policy control applied", "Blocked"]]}/>;
export const ContentApprovalQueue = ({ action }: { action: Action }) => <List title="Approval Queue" subtitle="Evidence-backed drafts awaiting an authorized human decision." action={action} items={[["Weekly rewards guide", "Content owner approval", "Pending"], ["Merchant launch copy", "Commerce and brand approval", "Pending"], ["KYC education update", "Compliance approval", "Review"], ["Cashback email series", "Approved by content owner", "Approved"]]}/>;
export const ContentSources = ({ action }: { action: Action }) => <List title="Content Sources" subtitle="Approved references with ownership, freshness and permitted-use controls." action={action} items={[["Glonni brand guide", "Internal · current version", "Approved"], ["Offer terms database", "Internal verified source", "Approved"], ["Provider product feeds", "Approved structured data", "Ready"], ["Unverified public article", "Not approved for factual claims", "Blocked"]]}/>;
export const ContentTasks = () => <List title="Content Tasks" subtitle="Traceable assignments owned by the Content Manager Agent." items={[["Prepare weekly content plan", "Due 16:00 IST", "Ready"], ["Revise merchant launch copy", "Waiting for commerce feedback", "Review"], ["Check expiring campaign terms", "Due now", "Critical"]]}/>;
export const ContentReports = () => <List title="Content Reports" subtitle="Operational reports delivered to Chief Operations and approved department owners." items={[["Daily publishing readiness", "18:00 IST", "Ready"], ["Weekly content throughput", "Monday 09:00 IST", "Ready"], ["Approval turnaround", "Weekly", "Scheduled"], ["Source freshness exceptions", "Daily", "Review"]]}/>;
export const ContentApprovals = ({ action }: { action: Action }) => <ContentApprovalQueue action={action}/>;
export const ContentAutomations = ({ action }: { action: Action }) => <List title="Content Automations" subtitle="Planning, reminders and checks only; never autonomous publication or approval." action={action} items={[["Source freshness scan", "Every 6 hours", "Scheduled"], ["Calendar deadline reminders", "Every hour", "Scheduled"], ["Brand and claims pre-check", "When draft changes", "Ready"], ["Daily content brief", "18:00 IST", "Ready"]]}/>;
export const ContentActivity = () => <List title="Content Activity History" subtitle="Read-only planning, drafting, source, approval and publishing evidence." items={[["Campaign copy revised", "Version 3 retained", "5 min ago"], ["Unapproved claim blocked", "Policy safeguard", "17 min ago"], ["Content brief submitted", "Content Manager Agent", "31 min ago"], ["Email series approved", "Content owner", "1 hr ago"]]}/>;
export const ContentConnections = ({ action }: { action: Action }) => <div className="grid gap-5 lg:grid-cols-2"><List title="Content Sources" subtitle="Read-only approved brand, offer, product and policy sources." action={action} items={[["Brand library", "Approved copy and terminology", "Ready"], ["Commerce catalog", "Product facts and deal terms", "Ready"], ["Campaign database", "Offer and reward conditions", "Ready"], ["Publishing channels", "Approval-gated access", "Pending"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><CalendarDays size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">What you provide</h2><p className="mt-2 text-xs leading-5 text-amber-900">Brand guide, approved terminology, audience rules, content channels, campaign facts, legal disclaimers, source owners, review roles and publishing schedules. Account credentials stay in secure connections—not agent chat.</p></article></div>;
export const ContentSettings = () => <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Content schedules and review requirements." items={[["Calendar review", "Daily at 09:00 IST", "Scheduled"], ["Source freshness limit", "30 days", "Ready"], ["Approval reminder", "After 4 hours", "Ready"], ["Executive report", "18:00 IST", "Ready"]]}/><List title="Safety & Permissions" subtitle="Protected actions the agent cannot perform alone." items={[["Publish any content", "Authorized human", "Blocked"], ["Approve own draft", "Separation of duties", "Blocked"], ["Make financial or legal claim", "Compliance approval", "Blocked"], ["Change brand rules", "Owner approval", "Blocked"], ["Use unapproved source", "Never permitted", "Blocked"]]}/></div>;
