"use client";

import { CheckCircle2, Image as ImageIcon, ShieldCheck, Video } from "lucide-react";
type Action = (message: string) => void;
const specialists = [["Graphic Design", "Creates supervised design drafts, formats, image variants and export packages from approved briefs and brand assets."], ["Video & Motion", "Creates supervised storyboards, edit plans, captions, motion drafts and platform-ready render packages."]];
const tone = (state: string) => state === "Blocked" || state === "Critical" ? "bg-rose-50 text-rose-700" : state === "Review" || state === "Pending" ? "bg-amber-50 text-amber-700" : state === "Ready" || state === "Approved" || state === "Rendering" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600";
function List({ title, subtitle, items, action }: { title: string; subtitle: string; items: string[][]; action?: Action }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name, detail, state]) => <article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><CheckCircle2 size={16}/></span><div className="min-w-0"><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${tone(state)}`}>{state}</span>{action && <button onClick={() => action(`${name} opened for supervised creative review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>; }

export function CreativeProductionOverview({ onOpen }: { onOpen: (tab: string) => void }) { return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Open requests", "18", "5 high priority"], ["Design drafts", "34", "Awaiting review"], ["Video projects", "9", "3 rendering"], ["Approval queue", "11", "Human decision"]].map(([label, value, note]) => <article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><div><h2 className="font-bold">Creative specialist team</h2><p className="mt-1 text-xs text-slate-500">Two focused subagents reporting to Creative Production.</p></div><button onClick={() => onOpen("Subagents")} className="ml-auto text-xs font-bold text-violet-700">Manage team →</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{specialists.map(([name, duty], index) => <article key={name} className="rounded-2xl border p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600">{index ? <Video size={18}/> : <ImageIcon size={18}/>}</span><span className="mt-4 block text-[9px] font-bold text-violet-600">SPECIALIST 0{index + 1}</span><h3 className="mt-2 text-sm font-bold">{name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{duty}</p></article>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human release boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">Agents may prepare briefs, drafts, variants, checks and export packages. They cannot publish, approve their own work, change brand assets, license media, create impersonations or replace an approved final asset without human authorization.</p></article></section></div>; }
export const CreativeRequests = ({ action }: { action: Action }) => <List title="Creative Requests" subtitle="Approved briefs, formats, owners, deadlines, source assets and required reviewers." action={action} items={[["Festival cashback campaign", "6 designs + 2 motion variants", "Ready"], ["Merchant launch kit", "Logo usage confirmation needed", "Review"], ["Reward explainer video", "Storyboard approved", "Rendering"], ["Celebrity likeness request", "Rights evidence unavailable", "Blocked"]]}/>;
export const DesignLibrary = ({ action }: { action: Action }) => <List title="Design Library" subtitle="Versioned design drafts, approved finals and export packages." action={action} items={[["Festival hero banners", "Version 4 · 6 formats", "Review"], ["Cashback icon set", "Approved master assets", "Approved"], ["Merchant social tiles", "12 variants prepared", "Ready"], ["Old logo exports", "Superseded brand version", "Blocked"]]}/>;
export const VideoLibrary = ({ action }: { action: Action }) => <List title="Video Library" subtitle="Storyboards, source timelines, captions, renders and approved masters." action={action} items={[["Rewards explainer", "45 sec · captions attached", "Rendering"], ["App walkthrough", "Version 2 · review copy", "Review"], ["Merchant promo cutdowns", "9:16, 1:1 and 16:9", "Ready"], ["Unlicensed music draft", "Rights control applied", "Blocked"]]}/>;
export const BrandReview = ({ action }: { action: Action }) => <List title="Brand Review" subtitle="Logo, colour, typography, imagery, tone, claims and accessibility checks." action={action} items={[["Festival hero banners", "Colour and spacing passed", "Ready"], ["Merchant launch animation", "Logo clear-space issue", "Review"], ["Rewards explainer captions", "Accessibility check passed", "Approved"], ["Old brand template", "Use prevented", "Blocked"]]}/>;
export const CreativeApprovalQueue = ({ action }: { action: Action }) => <List title="Approval Queue" subtitle="Creative evidence and previews awaiting authorized human decisions." action={action} items={[["Festival campaign exports", "Creative owner approval", "Pending"], ["Rewards explainer final", "Content and compliance review", "Pending"], ["Merchant social tiles", "Brand review complete", "Review"], ["Cashback icon update", "Approved by brand owner", "Approved"]]}/>;
export const CreativeTasks = () => <List title="Creative Tasks" subtitle="Traceable assignments for Creative Production and both specialists." items={[["Export festival formats", "Graphic Design · due 16:00", "Ready"], ["Render captioned video", "Video & Motion · 32 min", "Rendering"], ["Correct logo clear space", "Graphic Design · due now", "Critical"]]}/>;
export const CreativeReports = () => <List title="Creative Reports" subtitle="Production summaries delivered to Content Manager and Chief Operations." items={[["Daily production status", "18:00 IST", "Ready"], ["Weekly asset throughput", "Monday 09:00 IST", "Ready"], ["Revision and approval time", "Weekly", "Ready"], ["Brand exceptions", "Daily", "Review"]]}/>;
export const CreativeApprovals = ({ action }: { action: Action }) => <CreativeApprovalQueue action={action}/>;
export const CreativeAutomations = ({ action }: { action: Action }) => <List title="Creative Automations" subtitle="Checks, previews and reminders only; no autonomous release, licensing or brand changes." action={action} items={[["Asset specification check", "On every upload", "Ready"], ["Brand pre-check", "On every revision", "Ready"], ["Deadline reminders", "Every hour", "Ready"], ["Daily creative brief", "18:00 IST", "Ready"]]}/>;
export const CreativeActivity = () => <List title="Creative Activity History" subtitle="Read-only request, version, review, approval and export evidence." items={[["Design version uploaded", "Festival banners · v4", "4 min ago"], ["Unlicensed audio blocked", "Rights safeguard", "16 min ago"], ["Video render completed", "Rewards explainer", "29 min ago"], ["Icon set approved", "Brand owner", "1 hr ago"]]}/>;
export const CreativeConnections = ({ action }: { action: Action }) => <div className="grid gap-5 lg:grid-cols-2"><List title="Creative Connections" subtitle="Approved storage, brand libraries, rendering and review services." action={action} items={[["Brand asset library", "Read-only approved masters", "Ready"], ["Creative file storage", "Versioned project assets", "Ready"], ["Video rendering service", "Approval-gated exports", "Ready"], ["Licensed media library", "Rights metadata required", "Review"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><ImageIcon size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">What you provide</h2><p className="mt-2 text-xs leading-5 text-amber-900">Brand kit, logos, fonts, templates, approved examples, asset-storage access, output sizes, accessibility rules, licensed media sources, reviewers and deadlines. Credentials and licensed originals stay in secure storage—not agent chat.</p></article></div>;
export const CreativeSettings = () => <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Production defaults and review thresholds." items={[["Design review reminder", "After 4 hours", "Ready"], ["Video caption requirement", "Always", "Ready"], ["Master asset retention", "Indefinite", "Ready"], ["Daily report", "18:00 IST", "Ready"]]}/><List title="Safety & Permissions" subtitle="Protected actions agents cannot perform alone." items={[["Publish or distribute asset", "Authorized human", "Blocked"], ["Approve own creative", "Separation of duties", "Blocked"], ["Change brand masters", "Brand owner", "Blocked"], ["License media", "Human contract review", "Blocked"], ["Create impersonation", "Never permitted", "Blocked"]]}/></div>;
