"use client";
import { BarChart3, CheckCircle2, ShieldCheck } from "lucide-react";
type Action=(message:string)=>void;
const tone=(s:string)=>s==="Critical"||s==="Blocked"?"bg-rose-50 text-rose-700":s==="Review"||s==="Pending"?"bg-amber-50 text-amber-700":s==="Ready"||s==="Current"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600";
function List({title,subtitle,items,action}:{title:string;subtitle:string;items:string[][];action?:Action}){return <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([n,d,s])=><article key={n} className="flex items-center gap-3 p-5"><CheckCircle2 size={16} className="text-violet-600"/><div><b className="text-xs">{n}</b><p className="mt-1 text-[10px] text-slate-400">{d}</p></div><span className={`ml-auto rounded-full px-2 py-1 text-[9px] font-bold ${tone(s)}`}>{s}</span>{action&&<button onClick={()=>action(`${n} opened for governed analysis review`)} className="text-xs font-bold text-violet-700">View</button>}</article>)}</div></section>}
export function DataAnalystOverview({onOpen}:{onOpen:(tab:string)=>void}){return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Revenue today","₹18.4L","Verified sources"],["Active users","84,260","30-day"],["Data freshness","12 min","Within SLA"],["Insights to review","8","Executive decisions"]].map(([l,v,n])=><article key={l} className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-2xl font-bold">{v}</p><p className="text-[10px] text-slate-400">{n}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Company intelligence</h2><p className="mt-1 text-xs text-slate-500">Evidence-backed metrics, trends, comparisons and forecasts across approved datasets.</p><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Measure","Apply governed definitions to verified data."],["Explain","Trace drivers, changes and uncertainty."],["Recommend","Send evidence and options to Operations and CEO."]].map(([n,d],i)=><article key={n} className="rounded-xl border p-4"><b className="text-xs text-violet-700">0{i+1} {n}</b><p className="mt-2 text-xs text-slate-500">{d}</p></article>)}</div><button onClick={()=>onOpen("Business Dashboard")} className="mt-4 text-xs font-bold text-violet-700">Open dashboard →</button></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck className="text-violet-700"/><h2 className="mt-3 font-bold">Read-only decision boundary</h2><p className="mt-2 text-xs leading-5">The agent analyses approved datasets and recommends actions. It cannot alter source data, ledgers, balances, budgets, risk decisions, targets or metric definitions.</p></article></section></div>}
export const BusinessDashboard=({action}:{action:Action})=><List title="Business Dashboard" subtitle="Governed company KPIs with freshness and source lineage." action={action} items={[["Gross revenue","₹18.4L today","Current"],["Reward liability","₹6.2L","Current"],["Net contribution","₹8.7L","Ready"],["Stale provider feed","One source over SLA","Review"]]}/>;
export const RevenueAnalytics=({action}:{action:Action})=><List title="Revenue Analytics" subtitle="Revenue, cost, margin, reconciliation and cohort trends." action={action} items={[["Ads revenue","+8.4% week over week","Ready"],["Affiliate commission","3 exceptions excluded","Review"],["Reward cost ratio","33.7%","Current"],["Unreconciled revenue","Finance review","Pending"]]}/>;
export const UserAnalytics=({action}:{action:Action})=><List title="User Analytics" subtitle="Privacy-safe activation, retention, engagement and cohort analysis." action={action} items={[["30-day active users","84,260","Current"],["Week-one retention","38.2%","Ready"],["Reward completion funnel","4.8% drop detected","Review"],["Individual user profiling","Not permitted","Blocked"]]}/>;
export const MarketingAnalytics=({action}:{action:Action})=><List title="Marketing Analytics" subtitle="Acquisition, attribution, ROAS and channel incrementality." action={action} items={[["Blended ROAS","3.4×","Current"],["Acquisition CPA","₹118","Ready"],["Attribution gap","6.1% unmatched","Review"],["Unapproved causal claim","Evidence insufficient","Blocked"]]}/>;
export const RiskAnalytics=({action}:{action:Action})=><List title="Risk Analytics" subtitle="Aggregated risk trends without changing individual case decisions." action={action} items={[["High-risk rate","0.82%","Current"],["Withdrawal review load","+12% weekly","Review"],["False-positive sample","Analyst review ready","Ready"],["Individual risk override","Not permitted","Blocked"]]}/>;
export const Forecasts=({action}:{action:Action})=><List title="Forecasts" subtitle="Versioned scenarios with assumptions, intervals and backtesting." action={action} items={[["30-day revenue forecast","₹5.4Cr · 80% interval","Ready"],["Reward liability forecast","₹1.8Cr","Ready"],["Marketing scenario","Budget approval assumptions","Review"],["Point estimate without range","Quality control applied","Blocked"]]}/>;
export const AnalystTasks=()=> <List title="Analyst Tasks" subtitle="Traceable analysis assignments." items={[["Prepare daily executive brief","18:00 IST","Ready"],["Investigate retention change","Due 16:00","Review"],["Validate revenue anomaly","Due now","Critical"]]}/>;
export const AnalystReports=()=> <List title="Analyst Reports" subtitle="Versioned reports for Chief Operations and CEO." items={[["Daily business summary","18:00 IST","Ready"],["Weekly operating review","Monday","Ready"],["Monthly board metrics","Month end","Pending"],["Anomaly report","As detected","Review"]]}/>;
export const AnalystApprovals=({action}:{action:Action})=><List title="Analysis Approvals" subtitle="Approval for metric definitions, executive delivery and sensitive exports." action={action} items={[["New KPI definition","Owner review","Pending"],["CEO forecast delivery","Assumptions attached","Review"],["Sensitive data export","Security approval","Blocked"],["Dashboard publication","Data owner approval","Pending"]]}/>;
export const AnalystAutomations=({action}:{action:Action})=><List title="Analysis Automations" subtitle="Read-only calculations and alerts; no source-system mutation." action={action} items={[["Data freshness monitor","Every 10 minutes","Ready"],["Anomaly detection","Hourly","Ready"],["Forecast refresh","Daily","Ready"],["Executive brief","18:00 IST","Ready"]]}/>;
export const AnalystActivity=()=> <List title="Analysis Activity History" subtitle="Read-only query, dataset, report and delivery evidence." items={[["Revenue anomaly flagged","Finance handoff","5 min ago"],["Forecast refreshed","Model v12","18 min ago"],["Stale source excluded","Lineage retained","31 min ago"],["Weekly report approved","Data owner","1 hr ago"]]}/>;
export const AnalystConnections=({action}:{action:Action})=><div className="grid gap-5 lg:grid-cols-2"><List title="Data Connections" subtitle="Approved read-only datasets and semantic definitions." action={action} items={[["Revenue warehouse","Read-only governed views","Ready"],["Product analytics","Aggregated events","Ready"],["Marketing attribution","Read-only metrics","Ready"],["Risk aggregates","De-identified views","Ready"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><BarChart3 className="text-amber-700"/><h2 className="mt-3 font-bold">What you provide</h2><p className="mt-2 text-xs leading-5">Approved datasets, KPI definitions, owners, freshness SLAs, reporting periods, access classifications, forecast assumptions and report recipients. Connections remain read-only and credentials stay in the vault.</p></article></div>;
export const AnalystSettings=()=> <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Definitions, freshness and reporting thresholds." items={[["Freshness warning","30 minutes","Ready"],["Anomaly threshold","3 standard deviations","Ready"],["Forecast interval","80% and 95%","Ready"],["Executive report","18:00 IST","Ready"]]}/><List title="Safety & Permissions" subtitle="Protected mutations the analyst cannot perform." items={[["Modify source data","Never","Blocked"],["Change ledger or balance","Never","Blocked"],["Change budget or target","Human decision","Blocked"],["Override risk decision","Never","Blocked"],["Export sensitive records","Security approval","Blocked"]]}/></div>;
