"use client";

import { AlertTriangle, BadgeIndianRupee, CheckCircle2, Clock3, FileWarning, HandCoins, Link2, ReceiptIndianRupee, Scale, ShieldCheck } from "lucide-react";

type Action = (message: string) => void;

const specialists = [
  { name: "Rewards, Wallet & Reconciliation", icon: ReceiptIndianRupee, state: "Protected", load: 18, duty: "Matches verified provider callbacks to reward and wallet ledger entries, detects duplicates, reversals and mismatches, and prepares reconciliation evidence." },
  { name: "Withdrawals & Payouts", icon: HandCoins, state: "Review", load: 11, duty: "Monitors withdrawal eligibility, payout lifecycle, failures and settlement evidence; routes suspicious cases to Fraud & Risk." },
];

const exceptions = [
  ["FIN-10521", "Provider reward does not match wallet ledger", "Critical", "Rewards, Wallet & Reconciliation", "9 min"],
  ["FIN-10518", "Withdrawal awaiting settlement confirmation", "High", "Withdrawals & Payouts", "24 min"],
  ["FIN-10512", "Reward reversal after user credit", "High", "Rewards, Wallet & Reconciliation", "47 min"],
  ["FIN-10503", "Payout processor response delayed", "Medium", "Withdrawals & Payouts", "1h 12m"],
];

const tone = (value: string) => value === "Critical" || value === "Blocked" ? "bg-rose-50 text-rose-700" : value === "High" || value === "Review" || value === "Pending" ? "bg-amber-50 text-amber-700" : value === "Active" || value === "Ready" || value === "Matched" || value === "Approved" ? "bg-emerald-50 text-emerald-700" : value === "Protected" ? "bg-violet-50 text-violet-700" : "bg-slate-100 text-slate-600";

export function FinancePayoutOverview({ onOpen }: { onOpen: (tab: string) => void }) {
  return <div className="space-y-5">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Reconciliation exceptions","14","3 critical",FileWarning],["Withdrawals in review","11","2 due soon",Clock3],["Settlement mismatches","4","Needs evidence",Scale],["Ledger checks today","2,418","99.6% matched",CheckCircle2]].map(([label,value,note,Icon],index) => <article key={label as string} className="rounded-2xl border bg-white p-5 shadow-sm"><span className={`grid h-10 w-10 place-items-center rounded-xl ${index === 0 ? "bg-rose-50 text-rose-600" : "bg-violet-50 text-violet-600"}`}><Icon size={19}/></span><p className="mt-4 text-xs font-semibold text-slate-500">{label as string}</p><p className="mt-1 text-2xl font-bold">{value as string}</p><p className="mt-1 text-[10px] text-slate-400">{note as string}</p></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center border-b p-5"><div><h2 className="font-bold">Payments, wallet & finance team</h2><p className="mt-1 text-xs text-slate-500">Two specialist agents reconcile wallet evidence and prepare payout recommendations.</p></div><button onClick={() => onOpen("Subagents")} className="ml-auto text-xs font-bold text-violet-700">Manage team →</button></div><div className="grid gap-4 p-5 md:grid-cols-2">{specialists.map((agent,index) => <article key={agent.name} className="rounded-2xl border p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><agent.icon size={18}/></span><div><span className="text-[9px] font-bold text-violet-600">0{index + 1}</span><h3 className="text-sm font-bold">{agent.name}</h3></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{agent.duty}</p><p className="mt-3 text-[10px] font-semibold text-slate-400">{agent.load} active reviews</p></article>)}</div></article><div className="space-y-5"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><h2 className="font-bold">Needs attention</h2><span className="ml-auto rounded-full bg-rose-50 px-2 py-1 text-[9px] font-bold text-rose-700">4 ITEMS</span></div><div className="mt-4 space-y-3">{exceptions.slice(0,3).map(([id,label,severity]) => <button key={id} onClick={() => onOpen("Exceptions")} className="flex w-full items-center gap-3 rounded-xl border p-3 text-left"><AlertTriangle size={16} className="text-rose-600"/><div><b className="block text-xs">{label}</b><p className="text-[10px] text-slate-400">{id} · {severity}</p></div></button>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human money-movement boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">Agents may calculate, reconcile, investigate, route and recommend. Only authorized humans may release or cancel withdrawals, change payout details, manually credit or debit value, or approve exceptional financial adjustments.</p></article></div></section>
  </div>;
}

export function FinanceSubagents({ onInstruct }: { onInstruct: (name: string) => void }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Payments, wallet & finance specialist subagents</h2><p className="mt-1 text-xs text-slate-500">Narrow scopes keep wallet reconciliation and payout investigation separated and auditable.</p></div><div className="grid gap-4 p-5 lg:grid-cols-2">{specialists.map((agent,index) => <article key={agent.name} className="rounded-2xl border p-5"><span className="text-[9px] font-bold text-violet-600">SPECIALIST 0{index + 1}</span><h3 className="mt-1 text-sm font-bold">{agent.name}</h3><p className="mt-3 text-xs leading-5 text-slate-500">{agent.duty}</p><div className="mt-4 flex items-center border-t pt-4"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${tone(agent.state)}`}>{agent.state}</span><button onClick={() => onInstruct(agent.name)} className="ml-auto h-9 rounded-xl border border-violet-200 px-3 text-[10px] font-bold text-violet-700">Chat & instruct</button></div></article>)}</div></section>; }

function FinanceList({ title, subtitle, items, action }: { title: string; subtitle: string; items: string[][]; action?: Action }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name,detail,state]) => <article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-600"><BadgeIndianRupee size={16}/></span><div><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto rounded-full px-2 py-1 text-[9px] font-bold ${tone(state)}`}>{state}</span>{action && <button onClick={()=>action(`${name} opened for protected finance review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>; }

export const FinanceRewardsLedger = () => <FinanceList title="Rewards & Wallet Ledger" subtitle="Append-only reward and wallet evidence; provider events and corrections remain traceable." items={[["RW-48291","Verified provider completion · +₹18 equivalent","Matched"],["RW-48290","Survey completion · +₹12 equivalent","Matched"],["RW-48287","Provider reversal requires reconciliation","Review"]]}/>;
export const FinanceReconciliation = ({action}:{action:Action}) => <FinanceList title="Reconciliation" subtitle="Match provider evidence, platform wallet ledger and payout settlement without silently rewriting history." action={action} items={[["Daily provider-to-ledger match","99.6% matched","Active"],["Reward reversal batch","3 exceptions","Review"],["Affiliate return-window reconciliation","Statement pending","Pending"]]}/>;
export const FinanceWithdrawals = ({action}:{action:Action}) => <FinanceList title="Withdrawal Review" subtitle="Eligibility and evidence review only; agents cannot release funds." action={action} items={[["WD-18421 · ₹500","Eligibility passed · awaiting human release","Pending"],["WD-18419 · ₹1,000","Risk evidence requested","Review"],["WD-18414 · ₹250","Settlement confirmed","Matched"]]}/>;
export const FinancePayouts = ({action}:{action:Action}) => <FinanceList title="Payout Operations" subtitle="Track processor lifecycle and settlement evidence. Money movement remains human-authorized." action={action} items={[["PAY-8812","Processor accepted · settlement pending","Pending"],["PAY-8808","Settlement matched","Matched"],["PAY-8799","Processor response requires review","Review"]]}/>;
export const FinanceExceptions = ({action}:{action:Action}) => <FinanceList title="Payments & Wallet Exceptions" subtitle="Evidence-ranked mismatches requiring investigation or an authorized decision." action={action} items={exceptions.map(([id,title,level,,age])=>[`${id} · ${title}`,`Waiting ${age}`,level])}/>;
export const FinanceTasks = () => <FinanceList title="Payments & Wallet Tasks" subtitle="Traceable operational work with a responsible specialist." items={[["Resolve provider reward mismatch","Rewards, Wallet & Reconciliation · due now","Critical"],["Verify delayed payout settlement","Withdrawals & Payouts · 24 min","High"],["Prepare daily finance close","Main agent · today","Ready"]]}/>;
export const FinanceReports = () => <FinanceList title="Payments & Finance Reports" subtitle="Operational finance intelligence; not a substitute for statutory accounting." items={[["Daily reward reconciliation","Today 18:00 IST","Active"],["Daily withdrawal settlement report","Today 19:00 IST","Active"],["Weekly provider margin report","Monday 09:00 IST","Ready"],["Exception and reversal trends","Last 30 days","Review"]]}/>;
export const FinanceApprovals = ({action}:{action:Action}) => <FinanceList title="Payments & Wallet Approvals" subtitle="The agent supplies evidence and a recommendation; an authorized human makes the decision." action={action} items={[["Release withdrawal WD-18421","₹500 · eligibility passed","Pending"],["Manual reward correction","FIN-10521 · evidence prepared","Pending"],["Cancel payout","Owner/Finance authority required","Protected"],["Change payout destination","Never autonomous","Blocked"]]}/>;
export const FinanceAutomations = ({action}:{action:Action}) => <FinanceList title="Payments & Wallet Automations" subtitle="Automations reconcile, route and report; they never move money." action={action} items={[["Provider reward reconciliation","Every verified callback","Active"],["Withdrawal eligibility scan","Every 10 minutes","Active"],["Settlement status refresh","Every 15 minutes","Review"],["Daily finance report","18:00 IST","Ready"]]}/>;
export const FinanceActivityHistory = () => <FinanceList title="Payments & Wallet Activity History" subtitle="Read-only evidence of reconciliations, recommendations and human decisions." items={[["Reward callback matched","RW-48291 · system","2 min ago"],["Withdrawal routed for review","WD-18421 · Payments Agent","8 min ago"],["Settlement evidence attached","PAY-8808 · system","16 min ago"]]}/>;
export const FinanceConnections = ({action}:{action:Action}) => <div className="grid gap-5 lg:grid-cols-2"><FinanceList title="Payments & Wallet Connections" subtitle="Provider-neutral server integrations; secrets never enter agent instructions." action={action} items={[["Reward provider callbacks","Existing signed provider stream","Ready"],["Payout processor","Server API · not selected","Protected"],["Affiliate settlement statements","Provider-neutral adapter","Review"],["Fraud & Risk Agent","Evidence escalation only","Ready"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><Link2 size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">Connection requirements</h2><p className="mt-2 text-xs leading-5 text-amber-900">Provider credentials stay server-side. Signed callbacks, idempotency keys, immutable provider references and settlement evidence are required before production activation.</p></article></div>;
export const FinanceSettings = () => <FinanceList title="Payments, Wallet & Finance Settings" subtitle="Safe defaults for reconciliation and payout operations." items={[["Money movement","Human approval required","Protected"],["Manual balance adjustment","Reason + approval + audit log","Protected"],["Duplicate provider reference","Reject and investigate","Active"],["Fraud escalation","Route to Fraud & Risk Agent","Active"],["Provider selection","No provider locked in","Ready"]]}/>;
