"use client";

import { Activity, AlertTriangle, CheckCircle2, Clock3, FileWarning, Fingerprint, Link2, Scale, Search, ShieldAlert, ShieldCheck, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { FraudRiskControl } from "./fraud-risk-control";

type Action = (message: string) => void;

const specialists = [
  { name: "Account & Device Investigation", icon: Fingerprint, state: "Protected", load: 14, duty: "Links accounts, devices, sessions, IP and location evidence; detects VPN, proxy, emulator, referral and login anomalies." },
  { name: "Transaction & Withdrawal Investigation", icon: WalletCards, state: "Review", load: 9, duty: "Examines transaction velocity, payment reuse, reward abuse, reversals, chargebacks, provider conversions and payout evidence." },
];

const reviewItems = [
  ["RSK-10482", "Account cluster across 4 devices", "Critical", "Account & Device Investigation", "12 min"],
  ["RSK-10481", "Withdrawal velocity outside baseline", "High", "Transaction & Withdrawal Investigation", "28 min"],
  ["RSK-10479", "Repeated provider conversion reversal", "High", "Transaction & Withdrawal Investigation", "51 min"],
  ["RSK-10476", "Login location changed after recovery", "Medium", "Account & Device Investigation", "1h 18m"],
];

const tone = (value: string) => value === "Critical" || value === "Blocked" ? "bg-rose-50 text-rose-700" : value === "High" || value === "Review" || value === "Pending" ? "bg-amber-50 text-amber-700" : value === "Active" || value === "Ready" || value === "Approved" ? "bg-emerald-50 text-emerald-700" : value === "Protected" ? "bg-violet-50 text-violet-700" : "bg-slate-100 text-slate-600";

export function FraudRiskOverview({ onOpen }: { onOpen: (tab: string) => void }) {
  return <div className="space-y-5">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Open risk cases","23","4 critical",ShieldAlert],["Human review queue","17","3 due soon",Clock3],["Appeals awaiting review","6","Oldest 7 hours",Scale],["Signals checked today","1,284","99.2% verified",Activity]].map(([label,value,note,Icon],index) => <article key={label as string} className="rounded-2xl border bg-white p-5 shadow-sm"><span className={`grid h-10 w-10 place-items-center rounded-xl ${index === 0 ? "bg-rose-50 text-rose-600" : "bg-violet-50 text-violet-600"}`}><Icon size={19}/></span><p className="mt-4 text-xs font-semibold text-slate-500">{label as string}</p><p className="mt-1 text-2xl font-bold">{value as string}</p><p className="mt-1 text-[10px] text-slate-400">{note as string}</p></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center border-b p-5"><div><h2 className="font-bold">Investigation team</h2><p className="mt-1 text-xs text-slate-500">Two focused subagents collect evidence and prepare recommendations.</p></div><button onClick={() => onOpen("Subagents")} className="ml-auto text-xs font-bold text-violet-700">Manage team →</button></div><div className="grid gap-4 p-5 md:grid-cols-2">{specialists.map((agent,index) => <article key={agent.name} className="rounded-2xl border p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><agent.icon size={18}/></span><div><span className="text-[9px] font-bold text-violet-600">0{index + 1}</span><h3 className="text-sm font-bold">{agent.name}</h3></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{agent.duty}</p><p className="mt-3 text-[10px] font-semibold text-slate-400">{agent.load} active evidence reviews</p></article>)}</div></article><div className="space-y-5"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><h2 className="font-bold">Needs attention</h2><span className="ml-auto rounded-full bg-rose-50 px-2 py-1 text-[9px] font-bold text-rose-700">4 ITEMS</span></div><div className="mt-4 space-y-3">{reviewItems.slice(0,3).map(([id,label,severity]) => <button key={id} onClick={() => onOpen("Review Queue")} className="flex w-full items-center gap-3 rounded-xl border p-3 text-left"><AlertTriangle size={16} className="text-rose-600"/><div><b className="block text-xs">{label}</b><p className="text-[10px] text-slate-400">{id} · {severity}</p></div></button>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human decision boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">Agents collect evidence, score risk and recommend action. Only authorized humans can restrict accounts, release or cancel withdrawals, decide appeals, reject KYC or permanently close accounts.</p></article></div></section>
  </div>;
}

export function FraudRiskSubagents({ onInstruct }: { onInstruct: (name: string) => void }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Fraud & Risk specialist subagents</h2><p className="mt-1 text-xs text-slate-500">Each specialist investigates a narrow evidence domain and reports to the Fraud & Risk Agent.</p></div><div className="grid gap-4 p-5 lg:grid-cols-2">{specialists.map((agent,index) => <article key={agent.name} className="rounded-2xl border p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><agent.icon size={18}/></span><div><span className="text-[9px] font-bold text-violet-600">SPECIALIST 0{index + 1}</span><h3 className="text-sm font-bold">{agent.name}</h3></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{agent.duty}</p><div className="mt-4 flex items-center border-t pt-4"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${tone(agent.state)}`}>{agent.state}</span><span className="ml-2 text-[10px] text-slate-400">{agent.load} workload items</span><button onClick={() => onInstruct(agent.name)} className="ml-auto h-9 rounded-xl border border-violet-200 px-3 text-[10px] font-bold text-violet-700">Chat & instruct</button></div></article>)}</div></section>; }

export function RiskCases({ action }: { action: Action }) { return <FraudRiskControl action={action}/>; }

export function RiskReviewQueue({ action }: { action: Action }) {
  const [query,setQuery] = useState(""); const [severity,setSeverity] = useState("All");
  const visible = useMemo(() => reviewItems.filter((item) => `${item[0]} ${item[1]} ${item[3]}`.toLowerCase().includes(query.toLowerCase()) && (severity === "All" || item[2] === severity)),[query,severity]);
  return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 lg:flex-row lg:items-center"><div><h2 className="font-bold">Human Review Queue</h2><p className="mt-1 text-xs text-slate-500">Evidence-ranked work awaiting assignment or an authorized decision.</p></div><label className="flex h-10 flex-1 items-center gap-2 rounded-xl border px-3 lg:ml-auto lg:max-w-sm"><Search size={14}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search review queue" className="w-full text-xs outline-none"/></label><select value={severity} onChange={(e)=>setSeverity(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-xs"><option>All</option><option>Critical</option><option>High</option><option>Medium</option></select></div><div className="divide-y">{visible.map(([id,title,level,owner,age]) => <article key={id} className="flex flex-col gap-3 p-5 md:flex-row md:items-center"><span className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-rose-600"><FileWarning size={17}/></span><div><b className="text-xs">{title}</b><p className="text-[10px] text-slate-400">{id} · Waiting {age}</p></div><span className={`w-fit rounded-full px-2 py-1 text-[9px] font-bold ${tone(level)}`}>{level}</span><p className="text-xs text-slate-500 md:ml-auto">{owner}</p><button onClick={()=>action(`${id} opened in protected human review`)} className="text-xs font-bold text-violet-700">Review →</button></article>)}</div></section>;
}

function RiskList({ title, subtitle, items, action }: { title: string; subtitle: string; items: string[][]; action?: Action }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name,detail,state]) => <article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-600"><CheckCircle2 size={16}/></span><div><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto rounded-full px-2 py-1 text-[9px] font-bold ${tone(state)}`}>{state}</span>{action && <button onClick={()=>action(`${name} opened for protected review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>; }

export const RiskAppeals = ({action}:{action:Action}) => <RiskList title="Risk Appeals" subtitle="User statements and evidence are reviewed independently; agents never decide an appeal." action={action} items={[["APL-2091 · Withdrawal restriction","Submitted 7 hours ago","Pending"],["APL-2088 · Account access restriction","Additional evidence received","Review"],["APL-2084 · Reward abuse decision","Assigned to human reviewer","Review"],["APL-2079 · Device link finding","Decision delivered","Approved"]]}/>;
export const RiskTasks = () => <RiskList title="Fraud & Risk Tasks" subtitle="Investigations remain traceable to evidence, deadlines and a responsible specialist." items={[["Validate four-account device cluster","Account & Device Investigation · due now","Critical"],["Reconcile withdrawal velocity evidence","Transaction & Withdrawal Investigation · 28 min","High"],["Prepare appeal evidence bundle","Main agent · today","Review"],["Sample resolved cases for drift","Main agent · weekly","Ready"]]}/>;
export const RiskReports = () => <RiskList title="Fraud & Risk Reports" subtitle="Operational intelligence for the Fraud & Risk Lead and Chief Operations Agent." items={[["Daily risk summary","Today 18:00 IST","Active"],["Weekly fraud pattern report","Monday 09:00 IST","Active"],["False-positive analysis","Last 30 days","Ready"],["Withdrawal abuse trends","9 evidence clusters","Review"],["Rule performance report","Accuracy and appeal outcomes","Ready"]]}/>;
export const RiskRules = ({action}:{action:Action}) => <RiskList title="Risk Rules" subtitle="Versioned detection rules create signals and reviews; enforcement remains separately approved." action={action} items={[["Shared device account cluster","4+ linked accounts in 24 hours","Active"],["Withdrawal velocity anomaly","3 attempts above baseline in 2 hours","Active"],["Provider conversion reversal","Repeated reversal after reward credit","Review"],["VPN or emulator observation","Evidence only — never auto-restrict","Protected"],["Permanent account closure","No automatic rule permitted","Blocked"]]}/>;
export const RiskApprovals = ({action}:{action:Action}) => <RiskList title="Fraud & Risk Approvals" subtitle="The agent supplies evidence and a recommendation; a qualified human makes the decision." action={action} items={[["Temporary withdrawal hold","RSK-10481 · evidence prepared","Pending"],["Account restriction","RSK-10482 · critical cluster","Pending"],["Appeal outcome","APL-2091 · independent review","Pending"],["Permanent account closure","Owner-only authority","Protected"]]}/>;
export const RiskAutomations = ({action}:{action:Action}) => <RiskList title="Fraud & Risk Automations" subtitle="Automations observe, score, route and report. They do not execute high-impact decisions." action={action} items={[["Verified signal routing","On every eligible signal","Active"],["Review deadline warning","Every 15 minutes","Active"],["Device linkage refresh","Hourly","Review"],["Withdrawal anomaly scan","Every 10 minutes","Review"],["Daily Chief Operations report","18:00 IST","Ready"]]}/>;
export const RiskActivityHistory = () => <RiskList title="Fraud & Risk Activity History" subtitle="Read-only evidence of signals, assignments, rule versions, recommendations and human decisions." items={[["Verified device signal routed","RSK-10482 · system","2 min ago"],["Review assigned","RSK-10481 · Risk Admin","8 min ago"],["Appeal evidence added","APL-2091 · human reviewer","17 min ago"],["Rule version approved","Withdrawal velocity v4","31 min ago"]]}/>;
export const RiskConnections = ({action}:{action:Action}) => <div className="grid gap-5 lg:grid-cols-2"><RiskList title="Evidence Connections" subtitle="Only verified provider data is admitted into protected investigations." action={action} items={[["Device intelligence provider","Server API + signed webhook","Review"],["Payment fraud provider","Server API","Review"],["Offerwall postbacks","Existing signed provider stream","Ready"],["Withdrawal processor","Read-only evidence scope","Protected"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><Link2 size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">Connection requirements</h2><p className="mt-2 text-xs leading-5 text-amber-900">Provide the provider name, documentation URL, approved event types, webhook signature method and server credential. Secrets stay in the server vault and never appear in the admin page or agent instructions.</p></article></div>;
export const RiskSettings = () => <div className="grid gap-5 lg:grid-cols-2"><RiskList title="Operating Settings" subtitle="Department investigation and review controls." items={[["Coverage","24/7 signal intake","Active"],["Critical review target","15 minutes","Active"],["Evidence retention","Policy-controlled","Protected"],["Risk-score calibration","Monthly human review","Review"]]}/><RiskList title="Safety & Permissions" subtitle="Non-negotiable decision boundaries." items={[["Apply account restriction","KYC/Risk admin or owner","Protected"],["Close account permanently","Owner only","Protected"],["Release or cancel withdrawal","Payments approval","Blocked"],["Reject KYC or decide appeal","Authorized human only","Blocked"],["Change active risk rule","Owner approval + version history","Protected"]]}/></div>;
