"use client";
import { useMemo, useState } from "react";
import { CheckCircle2, FlaskConical, ImageIcon, LockKeyhole, RotateCcw } from "lucide-react";
import { approvedModels, modelPolicyAssignments, modelPolicyVersion } from "../../lib/agents/runtime/model-policy";

export function ModelGovernancePanel() {
  const [filter,setFilter]=useState("all"); const [notice,setNotice]=useState("");
  const assignments=useMemo(()=>modelPolicyAssignments.filter(([,model])=>filter==="all"||model===filter),[filter]);
  return <section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2"><h2 className="font-bold">Model Policy</h2><span className="rounded-full bg-violet-50 px-2 py-1 text-[9px] font-bold text-violet-700">VERSION {modelPolicyVersion}</span></div><p className="mt-1 text-xs text-slate-500">CEO-approved models and agent assignments. Live calls remain disabled.</p></div><select aria-label="Filter assignments by model" value={filter} onChange={e=>setFilter(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-xs font-bold lg:ml-auto"><option value="all">All approved models</option>{Object.keys(approvedModels).map(id=><option key={id}>{id}</option>)}</select><button onClick={()=>setNotice("A model change starts as a draft, runs in simulation, requires CEO approval and preserves this version for rollback.")} className="flex h-10 items-center justify-center gap-2 rounded-xl border px-3 text-xs font-bold text-violet-700"><FlaskConical size={14}/>Request model change</button></div>
    {notice&&<div className="border-b border-violet-100 bg-violet-50 px-5 py-3 text-xs text-violet-800">{notice}</div>}
    <div className="grid gap-4 border-b p-5 md:grid-cols-3">{Object.values(approvedModels).map(model=><article key={model.id} className="rounded-xl border p-4"><div className="flex items-center"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-50 text-violet-700">{model.capability==="image_generation"?<ImageIcon size={16}/>:<CheckCircle2 size={16}/>}</span><span className="ml-auto rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">APPROVED</span></div><h3 className="mt-3 text-sm font-bold">{model.id}</h3><p className="mt-1 text-[10px] capitalize text-slate-500">{model.capability.replaceAll("_"," ")} · OpenAI</p><p className="mt-3 text-[10px] font-bold text-amber-700">LIVE DISABLED</p></article>)}</div>
    <div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">{assignments.map(([agent,model],index)=><article key={agent} className="flex items-center gap-3 rounded-xl border p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-50 text-[9px] font-bold text-slate-500">{String(index+1).padStart(2,"0")}</span><div className="min-w-0"><b className="block truncate text-xs">{agent}</b><p className="mt-1 text-[10px] text-violet-700">{model}</p></div><LockKeyhole size={14} className="ml-auto shrink-0 text-slate-300"/></article>)}</div>
    <div className="flex flex-col gap-3 border-t bg-slate-50 p-5 sm:flex-row sm:items-center"><RotateCcw size={16} className="text-slate-500"/><p className="text-xs text-slate-600"><b>No hidden fallback:</b> an unavailable or unapproved model blocks the run. Previous approved versions remain available for rollback.</p><button onClick={()=>setNotice("Rollback becomes available after a newer CEO-approved policy version exists.")} className="h-9 rounded-xl border bg-white px-3 text-xs font-bold text-slate-600 sm:ml-auto">Rollback history</button></div>
  </section>;
}
