"use client";

import { CheckCircle2, Link2, ShieldCheck } from "lucide-react";
type Action=(message:string)=>void;
const specialists=[
  {name:"Provider & Offer Operations",duty:"Monitors approved offerwall providers, imports survey and app-install drafts, validates eligibility, targeting, caps, dates and user-facing terms."},
  {name:"Task, Conversion & Reward Reconciliation",duty:"Matches signed conversions to task attempts, detects missing, duplicate or reversed events, and prepares reward exceptions for human review."},
];
const tone=(v:string)=>v==="Critical"||v==="Blocked"?"bg-rose-50 text-rose-700":v==="Review"||v==="Pending"||v==="Degraded"?"bg-amber-50 text-amber-700":v==="Ready"||v==="Active"||v==="Matched"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600";
function List({title,subtitle,items,action}:{title:string;subtitle:string;items:string[][];action?:Action}){return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name,detail,state])=><article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><CheckCircle2 size={16}/></span><div className="min-w-0"><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${tone(state)}`}>{state}</span>{action&&<button onClick={()=>action(`${name} opened for supervised offer review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>}
export function OfferwallOverview({onOpen}:{onOpen:(tab:string)=>void}){return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Approved providers","6","1 degraded"],["Live offers","214","Surveys and installs"],["Tasks today","18,420","96.8% reconciled"],["Conversion exceptions","23","Human review"]].map(([label,value,note])=><article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><div><h2 className="font-bold">Offerwall specialist team</h2><p className="mt-1 text-xs text-slate-500">Separated offer setup and conversion reconciliation duties.</p></div><button onClick={()=>onOpen("Subagents")} className="ml-auto text-xs font-bold text-violet-700">Manage team →</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{specialists.map((item,index)=><article key={item.name} className="rounded-2xl border p-5"><span className="text-[9px] font-bold text-violet-600">SPECIALIST 0{index+1}</span><h3 className="mt-2 text-sm font-bold">{item.name}</h3><p className="mt-3 text-xs leading-5 text-slate-500">{item.duty}</p></article>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human decision boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">Agents can import, validate, monitor, match and recommend. Provider activation, credentials, offer publishing, reward changes, wallet corrections, disputed screen-outs and paid-reward reversals require authorized human approval.</p></article></section></div>}
export const OfferProviders=({action}:{action:Action})=><List title="Offer Providers" subtitle="Provider readiness, feed health and signed callback status. Credentials remain server-side." action={action} items={[["Survey router A","API and callback mapping verified","Ready"],["Install network B","Offer feed healthy","Active"],["Offerwall provider C","Callback latency elevated","Degraded"],["Provider credentials","Encrypted vault reference","Protected"]]}/>;
export const OfferSurveys=({action}:{action:Action})=><List title="Surveys" subtitle="Eligibility, duration, quotas, rewards and screen-out handling." action={action} items={[["Indian Shopping Habits","18 min · ₹42 · quota 72%","Active"],["Mobile Network Experience","12 min · ₹28","Ready"],["Digital Payments Study","Eligibility mapping review","Review"],["Expired survey session","Human claim review required","Pending"]]}/>;
export const AppInstallOffers=({action}:{action:Action})=><List title="App-Install Offers" subtitle="Install, first-open and milestone offers with device and attribution safeguards." action={action} items={[["Finance app install","Install + first open · ₹55","Active"],["Puzzle game milestone","Reach level 10 · ₹90","Active"],["Shopping app signup","Attribution window review","Review"],["Duplicate device install","Fraud control applied","Blocked"]]}/>;
export const OfferTaskTracking=({action}:{action:Action})=><List title="Task Tracking" subtitle="User task attempts, expiry, provider status and immutable terms snapshots." action={action} items={[["16,940 completed tasks","Verified today","Matched"],["1,102 tasks in progress","Within allowed duration","Active"],["312 expired attempts","No conversion received","Closed"],["66 provider-pending tasks","Approaching SLA","Review"]]}/>;
export const ConversionReconciliation=({action}:{action:Action})=><List title="Conversion Reconciliation" subtitle="Signed provider conversions matched to attempts and reward evidence." action={action} items={[["17,821 conversions matched","Current daily batch","Matched"],["23 missing rewards","Provider completion present","Critical"],["31 duplicate callbacks","Idempotency protection applied","Blocked"],["8 paid-reward reversals","Finance and risk approval required","Pending"]]}/>;
export const OfferTasks=()=> <List title="Offerwall Tasks" subtitle="Traceable assignments for the main agent and specialists." items={[["Validate survey feed changes","Provider & Offer Operations · due now","Review"],["Investigate missing rewards","Task & Reconciliation · 12 min","Critical"],["Prepare offer health summary","Offerwall & Tasks Agent · 18:00 IST","Ready"]]}/>;
export const OfferReports=()=> <List title="Offerwall Reports" subtitle="Operational summaries delivered to Chief Operations." items={[["Daily offer health","18:00 IST","Active"],["Conversion exceptions","Every 4 hours","Ready"],["Weekly provider performance","Monday 09:00 IST","Ready"],["Screen-out quality","Weekly","Review"]]}/>;
export const OfferApprovals=({action}:{action:Action})=><List title="Offerwall Approvals" subtitle="Agents prepare evidence; authorized humans make protected decisions." action={action} items={[["Activate survey provider","Signed callback test required","Pending"],["Publish install campaign","Terms and attribution attached","Pending"],["Change task reward","Owner approval required","Protected"],["Paid reward reversal","Finance and risk review","Critical"]]}/>;
export const OfferAutomations=({action}:{action:Action})=><List title="Offerwall Automations" subtitle="Monitoring and reporting only; no autonomous provider activation, reward change or wallet correction." action={action} items={[["Offer feed health scan","Every 10 minutes","Active"],["Task expiry monitor","Every 5 minutes","Active"],["Conversion mismatch detector","Every 15 minutes","Active"],["Daily operations brief","18:00 IST","Ready"]]}/>;
export const OfferActivity=()=> <List title="Offerwall Activity History" subtitle="Read-only provider, offer, task, conversion and approval evidence." items={[["Missing reward escalated","Task ATT-91842 · specialist 02","3 min ago"],["Survey feed validated","Provider A · specialist 01","11 min ago"],["Duplicate callback blocked","Idempotency control","18 min ago"],["Offer publish approved","Operations owner","42 min ago"]]}/>;
export const OfferConnections=({action}:{action:Action})=><div className="grid gap-5 lg:grid-cols-2"><List title="API Connections" subtitle="Approved provider feeds, reporting APIs and signed callback endpoints." action={action} items={[["Survey catalog API","Read-only offer import","Ready"],["App-install feed API","Read-only campaign import","Active"],["Signed conversion callback","HMAC-SHA256 · replay protected","Active"],["Credential vault","No agent-chat access","Protected"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><Link2 size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">What you provide</h2><p className="mt-2 text-xs leading-5 text-amber-900">Provider name, documentation, offer-feed and reporting endpoints, callback specification, event mappings, allowed IPs and server credential. Secrets go to the encrypted vault, never agent instructions.</p></article></div>;
export const OfferSettings=()=> <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Monitoring targets and escalation thresholds." items={[["Provider health check","Every 10 minutes","Active"],["Missing conversion escalation","After 30 minutes","Active"],["Offer cap warning","At 85%","Active"],["Daily report","18:00 IST","Ready"]]}/><List title="Safety & Permissions" subtitle="Protected actions agents cannot execute alone." items={[["Activate provider","Owner + AAL2","Protected"],["Publish offer","Owner approval","Protected"],["Change reward or terms","Owner approval","Blocked"],["Correct wallet or ledger","Finance workflow only","Blocked"],["Override fraud controls","Never permitted","Blocked"]]}/></div>;
