"use client";
import { CheckCircle2, ShieldCheck, TrendingUp } from "lucide-react";
type Action=(message:string)=>void;
const tone=(s:string)=>s==="Blocked"||s==="Critical"?"bg-rose-50 text-rose-700":s==="Review"||s==="Pending"?"bg-amber-50 text-amber-700":s==="Ready"||s==="Active"||s==="Approved"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600";
function List({title,subtitle,items,action}:{title:string;subtitle:string;items:string[][];action?:Action}){return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([n,d,s])=><article key={n} className="flex items-center gap-3 p-5"><CheckCircle2 size={16} className="text-violet-600"/><div><b className="text-xs">{n}</b><p className="mt-1 text-[10px] text-slate-400">{d}</p></div><span className={`ml-auto rounded-full px-2 py-1 text-[9px] font-bold ${tone(s)}`}>{s}</span>{action&&<button onClick={()=>action(`${n} opened for supervised marketing review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>}
export function PerformanceMarketingOverview({onOpen}:{onOpen:(tab:string)=>void}){return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Active campaigns","18","Across approved accounts"],["Spend today","₹84,200","Within approved caps"],["Blended ROAS","3.4×","7-day window"],["Need approval","6","Budget or targeting"]].map(([l,v,n])=><article key={l} className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-2xl font-bold">{v}</p><p className="text-[10px] text-slate-400">{n}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Performance operations</h2><p className="mt-1 text-xs text-slate-500">Monitor, diagnose, forecast and recommend across approved ad accounts.</p><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Observe","Spend, delivery, attribution and conversion quality."],["Optimize","Prepare audience, creative, bid and budget recommendations."],["Experiment","Design controlled tests with success and stop rules."]].map(([n,d],i)=><article key={n} className="rounded-xl border p-4"><b className="text-xs text-violet-700">0{i+1} {n}</b><p className="mt-2 text-xs text-slate-500">{d}</p></article>)}</div><button onClick={()=>onOpen("Advertising Campaigns")} className="mt-4 text-xs font-bold text-violet-700">Open campaigns →</button></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck className="text-violet-700"/><h2 className="mt-3 font-bold">Human spend boundary</h2><p className="mt-2 text-xs leading-5">The agent may analyse and recommend. Launching, increasing budgets, changing targeting, pausing major campaigns or committing spend requires authorized human approval.</p></article></section></div>}
export const AdvertisingCampaigns=({action}:{action:Action})=><List title="Advertising Campaigns" subtitle="Delivery, attribution and optimization recommendations." action={action} items={[["Rewards acquisition","Meta · ROAS 3.8×","Active"],["Merchant search","Google · CPA above target","Review"],["App reinstall","Draft campaign","Pending"],["Unverified landing page","Launch prevented","Blocked"]]}/>;
export const MarketingAudiences=({action}:{action:Action})=><List title="Audiences" subtitle="Approved audience definitions, exclusions and privacy controls." action={action} items={[["High-intent shoppers","Consent-safe segment","Ready"],["Lapsed earners","Frequency review","Review"],["KYC-derived targeting","Sensitive use prohibited","Blocked"],["Lookalike expansion","Owner approval required","Pending"]]}/>;
export const MarketingBudgets=({action}:{action:Action})=><List title="Budgets" subtitle="Approved caps, pacing and evidence-backed change requests." action={action} items={[["Daily portfolio cap","₹125,000 · 67% used","Ready"],["Merchant search increase","+₹12,500 recommended","Pending"],["Rewards campaign pacing","8% underspend","Review"],["Unapproved overspend","Hard cap enforced","Blocked"]]}/>;
export const MarketingTests=({action}:{action:Action})=><List title="A/B Tests" subtitle="Controlled hypotheses, variants, allocation, metrics and stop rules." action={action} items={[["Value message test","50/50 · CPA primary","Active"],["Landing-page hero","Draft hypothesis","Ready"],["Audience expansion","Risk review required","Pending"],["Test without stop rule","Activation prevented","Blocked"]]}/>;
export const CampaignApprovals=({action}:{action:Action})=><List title="Campaign Approvals" subtitle="Human decisions for spend, launch, targeting and major pauses." action={action} items={[["Increase Meta budget","+₹12,500 · evidence attached","Pending"],["Launch reinstall campaign","Creative and tracking ready","Review"],["Expand audience","Privacy review","Pending"],["Pause major campaign","CEO approval required","Critical"]]}/>;
export const MarketingTasks=()=> <List title="Marketing Tasks" subtitle="Traceable optimization work." items={[["Review search CPA","Due now","Critical"],["Prepare weekly forecast","Due 17:00","Ready"],["Validate attribution gap","Analytics handoff","Review"]]}/>;
export const MarketingReports=()=> <List title="Marketing Reports" subtitle="Performance reports to Chief Operations and CEO." items={[["Daily spend and ROAS","18:00 IST","Ready"],["Budget pacing","Every 4 hours","Active"],["Weekly experiment report","Monday","Ready"],["Attribution exceptions","Daily","Review"]]}/>;
export const MarketingApprovals=CampaignApprovals;
export const MarketingAutomations=({action}:{action:Action})=><List title="Marketing Automations" subtitle="Monitoring and recommendations only; no autonomous spend changes." action={action} items={[["Spend anomaly monitor","Every 5 minutes","Active"],["Budget pacing forecast","Hourly","Active"],["Test stop-rule alert","Every 15 minutes","Ready"],["Daily executive brief","18:00 IST","Ready"]]}/>;
export const MarketingActivity=()=> <List title="Marketing Activity History" subtitle="Read-only campaign, budget, audience, test and approval evidence." items={[["Budget change requested","Meta rewards","4 min ago"],["CPA alert raised","Merchant search","15 min ago"],["Sensitive audience blocked","Policy control","28 min ago"],["Test approved","Marketing owner","1 hr ago"]]}/>;
export const MarketingConnections=({action}:{action:Action})=><div className="grid gap-5 lg:grid-cols-2"><List title="Advertising Connections" subtitle="Minimum-permission ad accounts and analytics sources." action={action} items={[["Meta Ads","Read performance · gated changes","Ready"],["Google Ads","Read performance · gated changes","Ready"],["Attribution analytics","Read-only events","Ready"],["Credentials","Encrypted vault","Protected"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><TrendingUp className="text-amber-700"/><h2 className="mt-3 font-bold">What you provide</h2><p className="mt-2 text-xs leading-5">Ad-account access, conversion definitions, budget caps, ROAS/CPA targets, attribution rules, audience restrictions, approval owners and escalation thresholds. Credentials stay in the encrypted vault.</p></article></div>;
export const MarketingSettings=()=> <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Targets and alert thresholds." items={[["Spend scan","Every 5 minutes","Active"],["CPA warning","20% above target","Ready"],["ROAS warning","Below 2.0×","Ready"],["Daily report","18:00 IST","Ready"]]}/><List title="Safety & Permissions" subtitle="Protected actions." items={[["Launch campaign","Human approval","Blocked"],["Increase budget","Owner approval","Blocked"],["Change targeting","Owner + privacy review","Blocked"],["Pause major campaign","CEO approval","Blocked"],["Commit ad spend","Never autonomous","Blocked"]]}/></div>;
