"use client";
import { useState } from "react";
import { CirclePause, FlaskConical, LockKeyhole, Send } from "lucide-react";

type ShadowResult={modelId:string;outputText:string;inputTokens:number;outputTokens:number;estimatedCostUsd:number;durationMs:number};
export function ShadowPilotPanel(){
  const [agentName,setAgentName]=useState("Chief Operations Agent"),[objective,setObjective]=useState("Review current department readiness and propose the three most important follow-up actions for CEO review."),[result,setResult]=useState<ShadowResult|null>(null),[error,setError]=useState(""),[running,setRunning]=useState(false);
  async function run(){setRunning(true);setError("");setResult(null);try{const response=await fetch("/api/admin/agents/runtime/shadow",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentName,objective})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Shadow run failed.");setResult(body);}catch(cause){setError(cause instanceof Error?cause.message:"Shadow run failed.");}finally{setRunning(false);}}
  return <section className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><article className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-3"><FlaskConical className="text-violet-600"/><div><h2 className="font-bold">Controlled Shadow Pilot</h2><p className="text-xs text-slate-500">Real model response, recommendation only, with no tools or business actions.</p></div></div><label className="mt-5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Pilot agent<select value={agentName} onChange={e=>setAgentName(e.target.value)} className="mt-2 h-10 w-full rounded-xl border bg-white px-3 text-xs normal-case tracking-normal"><option>Chief Operations Agent</option><option>Support Team Lead Agent</option></select></label><label className="mt-3 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Shadow objective<textarea value={objective} onChange={e=>setObjective(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border p-3 text-xs normal-case tracking-normal"/></label><button disabled={running||objective.trim().length<10} onClick={()=>void run()} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-900 text-xs font-bold text-white disabled:opacity-40"><Send size={14}/>{running?"Running protected test…":"Run controlled shadow test"}</button>{error&&<p role="alert" className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{error}</p>}</article><div className="space-y-5"><article className="rounded-2xl border border-rose-200 bg-rose-50 p-5"><CirclePause className="text-rose-700"/><h3 className="mt-3 font-bold text-rose-950">Activation locked</h3><p className="mt-2 text-xs leading-5 text-rose-900">The pilot endpoint is deployed disabled. A separate CEO-approved environment switch is required before it can spend tokens. Tools, publishing, messages, payments and data changes are always unavailable in shadow mode.</p></article>{result?<article className="rounded-2xl border bg-white p-5"><div className="flex items-center"><div><h3 className="font-bold">Shadow recommendation</h3><p className="mt-1 text-[10px] text-slate-500">{result.modelId} · {result.inputTokens} input · {result.outputTokens} output · ${result.estimatedCostUsd.toFixed(6)} · {result.durationMs}ms</p></div><LockKeyhole size={16} className="ml-auto text-emerald-600"/></div><p className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-700">{result.outputText}</p></article>:<article className="rounded-2xl border border-dashed bg-white p-8 text-center"><LockKeyhole className="mx-auto text-slate-300"/><p className="mt-3 text-xs text-slate-500">No model call has been made.</p></article>}</div></section>;
}
