"use client";

import { CheckCircle2, MessageCircle, ShieldCheck } from "lucide-react";
type Action = (message: string) => void;
const tone = (state: string) => state === "Blocked" || state === "Critical" ? "bg-rose-50 text-rose-700" : state === "Review" || state === "Pending" ? "bg-amber-50 text-amber-700" : state === "Ready" || state === "Approved" || state === "Scheduled" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600";
function List({ title, subtitle, items, action }: { title: string; subtitle: string; items: string[][]; action?: Action }) { return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([name, detail, state]) => <article key={name} className="flex items-center gap-3 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><CheckCircle2 size={16}/></span><div className="min-w-0"><b className="text-xs">{name}</b><p className="mt-1 text-[10px] text-slate-400">{detail}</p></div><span className={`ml-auto shrink-0 rounded-full px-2 py-1 text-[9px] font-bold ${tone(state)}`}>{state}</span>{action && <button onClick={() => action(`${name} opened for supervised social review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>; }

export function SocialMediaOverview({ onOpen }: { onOpen: (tab: string) => void }) { return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Connected channels", "5", "Approval gated"], ["Scheduled drafts", "24", "Next 14 days"], ["Conversations", "138", "12 need review"], ["Approval queue", "9", "Human decision"]].map(([label, value, note]) => <article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center"><div><h2 className="font-bold">Social operations</h2><p className="mt-1 text-xs text-slate-500">Prepare, review, schedule, listen and report across approved accounts.</p></div><button onClick={() => onOpen("Publishing Calendar")} className="ml-auto text-xs font-bold text-violet-700">Open calendar →</button></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Prepare", "Adapt approved content for each channel and audience."], ["Listen", "Classify mentions, comments and support or risk signals."], ["Improve", "Report performance and recommend tested changes."]].map(([name, duty], index) => <article key={name} className="rounded-2xl border p-4"><span className="text-[9px] font-bold text-violet-600">STAGE 0{index + 1}</span><h3 className="mt-2 text-sm font-bold">{name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{duty}</p></article>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck size={19} className="text-violet-700"/><h2 className="mt-3 font-bold text-violet-950">Human communication boundary</h2><p className="mt-2 text-xs leading-5 text-violet-900">The agent may prepare posts and replies, classify conversations, schedule approved drafts and recommend actions. Publishing, replying publicly, deleting or hiding comments, changing accounts and launching paid promotions require authorized human approval.</p></article></section></div>; }
export const PublishingCalendar = ({ action }: { action: Action }) => <List title="Publishing Calendar" subtitle="Approved-channel plan with campaign, audience, owner, date and approval state." action={action} items={[["Weekly rewards tips", "Instagram + Facebook · 24 Aug", "Scheduled"], ["Cashback education", "LinkedIn · 26 Aug", "Ready"], ["Safety reminder", "All channels · compliance review", "Review"], ["Merchant launch", "3 channels · creative pending", "Pending"]]}/>;
export const ScheduledPosts = ({ action }: { action: Action }) => <List title="Scheduled Posts" subtitle="Platform-specific drafts with content, assets, links and immutable approval evidence." action={action} items={[["Rewards tip carousel", "Instagram · approved for 10:00", "Approved"], ["Merchant announcement", "Facebook · owner review", "Pending"], ["Cashback explainer", "LinkedIn · link verified", "Ready"], ["Unverified earnings claim", "Publishing control applied", "Blocked"]]}/>;
export const SocialConversations = ({ action }: { action: Action }) => <List title="Social Conversations" subtitle="Mentions and comments classified for response, support, safety or risk escalation." action={action} items={[["Missing reward question", "Support handoff recommended", "Review"], ["Positive app feedback", "Thank-you reply drafted", "Ready"], ["Account detail posted publicly", "Privacy escalation", "Critical"], ["Threatening or abusive comment", "Safety review · no auto reply", "Blocked"]]}/>;
export const ContentPerformance = ({ action }: { action: Action }) => <List title="Content Performance" subtitle="Organic reach, engagement, clicks and approved experiment recommendations." action={action} items={[["Rewards education series", "8.4% engagement · improving", "Ready"], ["Merchant launch posts", "2.1% click-through", "Ready"], ["Video completion rate", "41% · hook test proposed", "Review"], ["Paid boost recommendation", "Marketing owner approval required", "Pending"]]}/>;
export const SocialTasks = () => <List title="Social Tasks" subtitle="Traceable work owned by the Social Media Agent." items={[["Prepare weekly channel plan", "Due 16:00 IST", "Ready"], ["Route reward questions", "12 conversations", "Review"], ["Verify expiring campaign links", "Due now", "Critical"]]}/>;
export const SocialReports = () => <List title="Social Reports" subtitle="Operational and performance summaries delivered to Content and Chief Operations." items={[["Daily publishing readiness", "09:00 IST", "Ready"], ["Conversation escalation report", "Every 4 hours", "Ready"], ["Weekly channel performance", "Monday 10:00 IST", "Ready"], ["Reply quality sample", "Weekly", "Review"]]}/>;
export const SocialApprovals = ({ action }: { action: Action }) => <List title="Social Approvals" subtitle="Evidence-backed posts, replies and protected changes awaiting human decisions." action={action} items={[["Publish merchant announcement", "Content owner approval", "Pending"], ["Reply to complaint", "Support-approved wording", "Review"], ["Hide abusive comment", "Account owner decision", "Pending"], ["Launch paid promotion", "Marketing and budget approval", "Blocked"]]}/>;
export const SocialAutomations = ({ action }: { action: Action }) => <List title="Social Automations" subtitle="Monitoring, classification and reminders only; no autonomous public action." action={action} items={[["Mention and comment sync", "Every 5 minutes", "Scheduled"], ["Conversation classification", "On ingestion", "Ready"], ["Approval reminders", "Every hour", "Ready"], ["Daily social brief", "18:00 IST", "Ready"]]}/>;
export const SocialActivity = () => <List title="Social Activity History" subtitle="Read-only post, conversation, approval, handoff and account evidence." items={[["Support question routed", "Conversation SOC-1842", "3 min ago"], ["Post draft revised", "Merchant launch · v3", "14 min ago"], ["Privacy exposure escalated", "No public reply sent", "22 min ago"], ["Carousel approved", "Content owner", "1 hr ago"]]}/>;
export const SocialConnections = ({ action }: { action: Action }) => <div className="grid gap-5 lg:grid-cols-2"><List title="Social Connections" subtitle="Approved social accounts with minimum permissions and encrypted credentials." action={action} items={[["Instagram business", "Read insights · approval-gated publish", "Ready"], ["Facebook page", "Read comments · approval-gated reply", "Ready"], ["LinkedIn page", "Read insights · draft scheduling", "Ready"], ["Account credentials", "Encrypted server vault", "Protected"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><MessageCircle size={19} className="text-amber-700"/><h2 className="mt-3 font-bold text-amber-950">What you provide</h2><p className="mt-2 text-xs leading-5 text-amber-900">Official account access, channel owners, approved reply templates, moderation rules, escalation contacts, publishing hours, audience rules and analytics permissions. Credentials are connected through the encrypted server vault—not agent chat.</p></article></div>;
export const SocialSettings = () => <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Monitoring, scheduling and escalation defaults." items={[["Conversation sync", "Every 5 minutes", "Scheduled"], ["Urgent escalation", "Within 5 minutes", "Ready"], ["Quiet publishing hours", "23:00–07:00 IST", "Ready"], ["Daily report", "18:00 IST", "Ready"]]}/><List title="Safety & Permissions" subtitle="Protected public actions the agent cannot execute alone." items={[["Publish post", "Authorized human", "Blocked"], ["Send public reply", "Authorized human", "Blocked"], ["Hide or delete comment", "Account owner", "Blocked"], ["Change account settings", "Owner + AAL2", "Blocked"], ["Launch paid promotion", "Marketing budget approval", "Blocked"]]}/></div>;
