"use client";
import { CheckCircle2, ServerCog, ShieldCheck } from "lucide-react";
type Action=(message:string)=>void;
const specialists=[["Application & Integration Engineer","Monitors application errors, APIs, provider integrations, queues and failed jobs; prepares fixes and test evidence."],["Database, Infrastructure & DevOps","Monitors databases, hosting, deployments, capacity, backups and security signals; prepares controlled change plans."]];
const tone=(s:string)=>s==="Critical"||s==="Blocked"?"bg-rose-50 text-rose-700":s==="Review"||s==="Pending"||s==="Degraded"?"bg-amber-50 text-amber-700":s==="Ready"||s==="Healthy"||s==="Verified"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600";
function List({title,subtitle,items,action}:{title:string;subtitle:string;items:string[][];action?:Action}){return <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div><div className="divide-y">{items.map(([n,d,s])=><article key={n} className="flex items-center gap-3 p-5"><CheckCircle2 size={16} className="text-violet-600"/><div><b className="text-xs">{n}</b><p className="mt-1 text-[10px] text-slate-400">{d}</p></div><span className={`ml-auto rounded-full px-2 py-1 text-[9px] font-bold ${tone(s)}`}>{s}</span>{action&&<button onClick={()=>action(`${n} opened for controlled technical review`)} className="text-xs font-bold text-violet-700">Review</button>}</article>)}</div></section>}
export function TechnicalOperationsOverview({onOpen}:{onOpen:(tab:string)=>void}){return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["System status","Healthy","12 services"],["Open incidents","3","1 high priority"],["Failed jobs","17","Retry review"],["Backup status","Verified","Last test 2 days"]].map(([l,v,n])=><article key={l} className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-500">{l}</p><p className="mt-2 text-2xl font-bold">{v}</p><p className="text-[10px] text-slate-400">{n}</p></article>)}</section><section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="rounded-2xl border bg-white p-5"><div className="flex"><div><h2 className="font-bold">Technical specialist team</h2><p className="text-xs text-slate-500">Separated application and infrastructure responsibilities.</p></div><button onClick={()=>onOpen("Subagents")} className="ml-auto text-xs font-bold text-violet-700">Manage team →</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{specialists.map(([n,d],i)=><article key={n} className="rounded-xl border p-5"><b className="text-xs text-violet-700">SPECIALIST 0{i+1}</b><h3 className="mt-2 text-sm font-bold">{n}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{d}</p></article>)}</div></article><article className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><ShieldCheck className="text-violet-700"/><h2 className="mt-3 font-bold">Human change boundary</h2><p className="mt-2 text-xs leading-5">Agents may monitor, diagnose, prepare fixes, test plans and recommendations. Production deploys, database changes, credential rotation, infrastructure changes, backup restores and destructive actions require authorized humans.</p></article></section></div>}
export const SystemHealth=({action}:{action:Action})=><List title="System Health" subtitle="Applications, APIs, databases, queues and infrastructure." action={action} items={[["Web application","99.98% availability","Healthy"],["Supabase database","Connections normal","Healthy"],["Provider callbacks","Latency elevated","Degraded"],["Queue backlog","Within threshold","Ready"]]}/>;
export const Incidents=({action}:{action:Action})=><List title="Incidents" subtitle="Severity, impact, evidence, ownership and response timeline." action={action} items={[["Callback delay","High · rewards delayed","Critical"],["Email retry spike","Medium · investigating","Review"],["Admin timeout","Low · fix prepared","Ready"],["Unverified production change","Execution blocked","Blocked"]]}/>;
export const Deployments=({action}:{action:Action})=><List title="Deployments" subtitle="Build, test, approval, release and rollback evidence." action={action} items={[["Current production","Commit f0cb3ac","Verified"],["Technical agent release","Tests required","Pending"],["Rollback plan","Last known good retained","Ready"],["Direct unapproved deploy","Policy blocked","Blocked"]]}/>;
export const FailedJobs=({action}:{action:Action})=><List title="Failed Jobs" subtitle="Queue failures, retry safety and idempotency evidence." action={action} items={[["Reward reconciliation","8 failures · safe retry","Review"],["Provider import","6 schema errors","Review"],["Daily report","3 timeout retries","Ready"],["Non-idempotent retry","Automatic retry blocked","Blocked"]]}/>;
export const SecurityAlerts=({action}:{action:Action})=><List title="Security Alerts" subtitle="Authentication, secrets, access, abuse and infrastructure signals." action={action} items={[["Failed admin sign-ins","Threshold alert","Review"],["Credential age","Rotation plan due","Pending"],["RLS advisor","No critical findings","Healthy"],["Secret exposed in chat","Immediate block and escalation","Critical"]]}/>;
export const Backups=({action}:{action:Action})=><List title="Backups" subtitle="Backup freshness, integrity, retention and restore-test evidence." action={action} items={[["Database backup","Current · encrypted","Verified"],["Asset metadata backup","Current","Verified"],["Restore rehearsal","Passed 2 days ago","Ready"],["Production restore","Human approval required","Blocked"]]}/>;
export const TechnicalTasks=()=> <List title="Technical Tasks" subtitle="Traceable assignments for both specialists." items={[["Investigate callback delay","Application Engineer · now","Critical"],["Review backup test","Infrastructure · 16:00","Ready"],["Prepare deployment plan","Technical Operations","Review"]]}/>;
export const TechnicalReports=()=> <List title="Technical Reports" subtitle="Operational reports to Chief Operations and CEO." items={[["Daily system health","18:00 IST","Ready"],["Incident summary","On resolution","Ready"],["Weekly reliability","Monday","Ready"],["Security posture","Daily","Review"]]}/>;
export const TechnicalApprovals=({action}:{action:Action})=><List title="Technical Approvals" subtitle="Human decisions for protected production changes." action={action} items={[["Deploy release","Tests and rollback attached","Pending"],["Database migration","Owner approval","Pending"],["Rotate credential","Security approval","Review"],["Restore production backup","Two-person approval","Critical"]]}/>;
export const TechnicalAutomations=({action}:{action:Action})=><List title="Technical Automations" subtitle="Monitoring and safe alerts only; no autonomous production mutation." action={action} items={[["Health checks","Every minute","Healthy"],["Failed-job detector","Every 5 minutes","Ready"],["Backup verification","Daily","Ready"],["Security scan","Hourly","Ready"]]}/>;
export const TechnicalActivity=()=> <List title="Technical Activity History" subtitle="Read-only health, incident, deployment, backup and approval evidence." items={[["Callback incident escalated","High severity","4 min ago"],["Backup verified","Integrity passed","19 min ago"],["Failed job quarantined","Unsafe retry blocked","31 min ago"],["Deployment approved","Technical owner","1 hr ago"]]}/>;
export const TechnicalConnections=({action}:{action:Action})=><div className="grid gap-5 lg:grid-cols-2"><List title="Technical Connections" subtitle="Read-only monitoring and approval-gated operational services." action={action} items={[["Vercel","Read deployments and logs","Ready"],["Supabase","Advisors and health","Ready"],["Error monitoring","Read events","Ready"],["Credential vault","No chat access","Protected"]]}/><article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><ServerCog className="text-amber-700"/><h2 className="mt-3 font-bold">What you provide</h2><p className="mt-2 text-xs leading-5">Service accounts, monitoring endpoints, owners, on-call contacts, severity rules, maintenance windows, backup policy, deployment approvals and rollback requirements. Credentials stay in the encrypted vault.</p></article></div>;
export const TechnicalSettings=()=> <div className="grid gap-5 lg:grid-cols-2"><List title="Operating Settings" subtitle="Reliability and escalation thresholds." items={[["Health interval","1 minute","Ready"],["High incident SLA","5 minutes","Ready"],["Backup verification","Daily","Ready"],["Executive report","18:00 IST","Ready"]]}/><List title="Safety & Permissions" subtitle="Protected actions." items={[["Deploy production","Human approval","Blocked"],["Modify database","Owner approval","Blocked"],["Rotate credentials","Security approval","Blocked"],["Restore backup","Two-person approval","Blocked"],["Destructive action","Never autonomous","Blocked"]]}/></div>;
