"use client";

import {
  ArrowLeft, BadgeCheck, Bell, CheckCircle2, ChevronRight, CircleHelp, CircleUserRound, ClipboardCheck, Copy,
  Coins, CreditCard, Download, Flame, Gamepad2, Gift, History,
  ExternalLink, Home, Landmark, LockKeyhole, Mail, Megaphone, MonitorPlay, Play, Search, ShieldCheck,
  ShoppingBag, Smartphone, Sparkles, Star, Store, Target, Timer, TrendingUp, Trophy, X,
  UserRoundPlus, Wallet, Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState } from "react";

type NavKey = "home" | "tasks" | "shop" | "games" | "profile";
type TaskKey = "watch" | "surveys" | "downloads";
type DetailKey = "notifications" | "referral" | "bonus" | "wallet" | "history" | "payout" | "kyc" | "support" | "stores" | null;

const navItems: { key: NavKey; label: string; icon: LucideIcon }[] = [
  { key: "home", label: "Home", icon: Home },
  { key: "tasks", label: "Tasks", icon: ClipboardCheck },
  { key: "shop", label: "Shop & Earn", icon: ShoppingBag },
  { key: "games", label: "Games", icon: Gamepad2 },
  { key: "profile", label: "Profile", icon: CircleUserRound },
];

const purple = "from-[#7357f2] via-[#6844e4] to-[#542bc9]";

export default function App() {
  const [activeNav, setActiveNav] = useState<NavKey>("home");
  const [taskTab, setTaskTab] = useState<TaskKey>("watch");
  const [watched, setWatched] = useState(12);
  const [toast, setToast] = useState("");
  const [detail, setDetail] = useState<DetailKey>(null);
  const [searchOpen, setSearchOpen] = useState(false);

  const navigate = (key: NavKey, tab?: TaskKey) => {
    setDetail(null);
    setActiveNav(key);
    if (tab) setTaskTab(tab);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const notify = (message: string) => {
    setToast(message);
    window.setTimeout(() => setToast(""), 2200);
  };

  return (
    <main className="mx-auto min-h-screen w-full max-w-[1180px] bg-[#fbfbfe] pb-28 md:my-5 md:min-h-[calc(100vh-2.5rem)] md:rounded-[32px] md:border md:border-white md:shadow-[0_28px_80px_rgba(50,35,95,.12)]">
      <Header activeNav={activeNav} detail={detail} onBack={() => setDetail(null)} onSearch={() => setSearchOpen(true)} onNotifications={() => setDetail("notifications")} />
      <section className="px-4 pb-4 md:px-8 lg:px-10">
        {detail ? <DetailScreen detail={detail} open={setDetail} notify={notify} /> : <>
          {activeNav === "home" && <HomeScreen navigate={navigate} open={setDetail} watched={watched} />}
          {activeNav === "tasks" && <TasksScreen active={taskTab} setActive={setTaskTab} watched={watched} setWatched={setWatched} notify={notify} />}
          {activeNav === "shop" && <ShopScreen notify={notify} open={setDetail} />}
          {activeNav === "games" && <GamesScreen notify={notify} />}
          {activeNav === "profile" && <ProfileScreen open={setDetail} />}
        </>}
      </section>
      <BottomNav active={activeNav} navigate={navigate} />
      {searchOpen && <GlobalSearch onClose={() => setSearchOpen(false)} navigate={navigate} open={setDetail} />}
      {toast && <div className="fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-full bg-[#1d1534] px-5 py-3 text-sm font-bold text-white shadow-xl">{toast}</div>}
    </main>
  );
}

function Header({ activeNav, detail, onBack, onSearch, onNotifications }: { activeNav: NavKey; detail: DetailKey; onBack: () => void; onSearch: () => void; onNotifications: () => void }) {
  const title = navItems.find((item) => item.key === activeNav)?.label;
  const detailTitles: Partial<Record<Exclude<DetailKey, null>, string>> = { notifications:"Notifications", referral:"Refer & Earn", bonus:"Daily Bonus", wallet:"Wallet", history:"Earning History", payout:"UPI / Bank Details", kyc:"KYC Verification", support:"Help & Support", stores:"All Stores" };
  return (
    <header className="sticky top-0 z-30 flex items-center justify-between bg-[#fbfbfe]/90 px-4 py-5 backdrop-blur-xl md:rounded-t-[32px] md:px-8 lg:px-10">
      <div>
        {detail ? <button onClick={onBack} className="flex items-center gap-2 text-left"><span className="grid h-9 w-9 place-items-center rounded-full border border-[#ebe8f3] bg-white"><ArrowLeft className="h-4 w-4"/></span><h1 className="text-xl font-extrabold tracking-tight text-[#181426]">{detailTitles[detail]}</h1></button> : activeNav === "home" ? <><p className="text-xs font-medium text-slate-500">Good morning,</p><h1 className="text-xl font-extrabold tracking-tight text-[#181426]">Shaneel <span aria-hidden>👋</span></h1></> : <h1 className="text-2xl font-extrabold tracking-tight text-[#181426]">{title}</h1>}
      </div>
      <div className="flex items-center gap-2">
        {activeNav !== "home" && <div className="flex items-center gap-1.5 rounded-full border border-[#ebe8f3] bg-white px-3 py-2 text-sm font-extrabold text-[#272034] shadow-sm"><Coins className="h-4 w-4 text-amber-400" fill="currentColor" /> 0</div>}
        {!detail && <button onClick={onSearch} aria-label="Search Glonni Ads" className="grid h-10 w-10 place-items-center rounded-full border border-[#ebe8f3] bg-white text-[#332c43] shadow-sm transition hover:border-violet-300 hover:text-violet-600"><Search className="h-5 w-5" /></button>}
        {!detail && <button onClick={onNotifications} aria-label="Notifications" className="relative grid h-10 w-10 place-items-center rounded-full border border-[#ebe8f3] bg-white text-[#332c43] shadow-sm"><Bell className="h-5 w-5" /><span className="absolute right-0 top-0 grid h-4 min-w-4 place-items-center rounded-full bg-rose-500 px-1 text-[9px] font-bold text-white">3</span></button>}
      </div>
    </header>
  );
}

function GlobalSearch({ onClose, navigate, open }: { onClose: () => void; navigate: (key: NavKey, tab?: TaskKey) => void; open: (detail: DetailKey) => void }) {
  const [query, setQuery] = useState("");
  const results = [
    { title: "Watch & Earn", group: "Tasks", keywords: "ads video reward", icon: MonitorPlay, action: () => navigate("tasks", "watch") },
    { title: "Surveys", group: "Tasks", keywords: "opinion questions", icon: ClipboardCheck, action: () => navigate("tasks", "surveys") },
    { title: "Download Apps", group: "Tasks", keywords: "install offers", icon: Download, action: () => navigate("tasks", "downloads") },
    { title: "Shop & Earn", group: "Shopping", keywords: "products compare amazon flipkart myntra ajio", icon: ShoppingBag, action: () => navigate("shop") },
    { title: "Partner Stores", group: "Shopping", keywords: "amazon flipkart myntra ajio croma", icon: Store, action: () => open("stores") },
    { title: "Games & Missions", group: "Games", keywords: "play challenge rewards", icon: Gamepad2, action: () => navigate("games") },
    { title: "Wallet", group: "Account", keywords: "balance withdraw money", icon: Wallet, action: () => open("wallet") },
    { title: "Earning History", group: "Account", keywords: "transactions rewards activity", icon: History, action: () => open("history") },
    { title: "UPI / Bank Details", group: "Account", keywords: "payout account withdrawal", icon: Landmark, action: () => open("payout") },
    { title: "KYC Verification", group: "Account", keywords: "pan identity verify", icon: ShieldCheck, action: () => open("kyc") },
    { title: "Help & Support", group: "Support", keywords: "faq ticket issue", icon: CircleHelp, action: () => open("support") },
    { title: "Refer & Earn", group: "Rewards", keywords: "invite friends referral", icon: UserRoundPlus, action: () => open("referral") },
    { title: "Daily Bonus", group: "Rewards", keywords: "check in streak gift", icon: Gift, action: () => open("bonus") },
  ];
  const normalized = query.trim().toLowerCase();
  const visible = results.filter(item => `${item.title} ${item.group} ${item.keywords}`.toLowerCase().includes(normalized));
  const select = (action: () => void) => { action(); onClose(); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <div className="fixed inset-0 z-[60] bg-[#171022]/45 p-3 backdrop-blur-sm sm:p-6" onMouseDown={onClose}>
    <section role="dialog" aria-modal="true" aria-label="Search Glonni Ads" onMouseDown={event => event.stopPropagation()} className="mx-auto mt-12 max-h-[80vh] w-full max-w-xl overflow-hidden rounded-[26px] border border-white/70 bg-[#fbfbfe] shadow-2xl sm:mt-20">
      <div className="flex items-center gap-3 border-b border-[#ebe8f2] p-4"><Search className="h-5 w-5 shrink-0 text-violet-600" /><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search tasks, products, games, wallet…" className="min-w-0 flex-1 bg-transparent text-sm font-medium text-[#241d34] outline-none placeholder:text-slate-400" />{query && <button onClick={() => setQuery("")} aria-label="Clear search" className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-slate-500"><X className="h-4 w-4" /></button>}<button onClick={onClose} className="text-xs font-extrabold text-violet-600">Close</button></div>
      <div className="max-h-[calc(80vh-72px)] overflow-y-auto p-3">{!query && <p className="px-2 pb-3 text-xs font-bold text-slate-400">POPULAR SEARCHES</p>}<div className="space-y-1">{visible.map(({ title, group, icon: Icon, action }) => <button key={title} onClick={() => select(action)} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left transition hover:bg-violet-50"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-100 text-violet-600"><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><b className="block text-sm text-[#282133]">{title}</b><span className="text-xs text-slate-500">{group}</span></span><ChevronRight className="h-4 w-4 text-slate-300" /></button>)}</div>{visible.length === 0 && <EmptyState icon={Search} title="No results found" body="Try a simpler word such as games, wallet, surveys or shopping." />}</div>
    </section>
  </div>;
}

function HomeScreen({ navigate, open, watched }: { navigate: (key: NavKey, tab?: TaskKey) => void; open: (detail:DetailKey)=>void; watched:number }) {
  const shortcuts = [
    { label: "Tasks", icon: ClipboardCheck, color: "bg-violet-100 text-violet-600", action: () => navigate("tasks") },
    { label: "Shop & Earn", icon: ShoppingBag, color: "bg-pink-100 text-pink-600", action: () => navigate("shop") },
    { label: "Games", icon: Gamepad2, color: "bg-indigo-100 text-indigo-600", action: () => navigate("games") },
    { label: "Refer & Earn", icon: UserRoundPlus, color: "bg-sky-100 text-sky-600", action: () => open("referral") },
    { label: "Surveys", icon: ClipboardCheck, color: "bg-emerald-100 text-emerald-600", action: () => navigate("tasks", "surveys") },
    { label: "Daily Bonus", icon: Gift, color: "bg-orange-100 text-orange-600", action: () => open("bonus") },
  ];
  const opportunities = [
    { title:"Watch a short ad", meta:"30 sec · Instant reward", reward:"₹0.80", icon:MonitorPlay, color:"bg-violet-100 text-violet-600", action:()=>navigate("tasks","watch") },
    { title:"Shopping habits", meta:"Survey · Around 8 min", reward:"₹12", icon:ClipboardCheck, color:"bg-emerald-100 text-emerald-600", action:()=>navigate("tasks","surveys") },
    { title:"Pocket Budget", meta:"Install and register", reward:"₹45", icon:Download, color:"bg-blue-100 text-blue-600", action:()=>navigate("tasks","downloads") },
  ];
  return <div className="space-y-6">
    <section className={`relative overflow-hidden rounded-[28px] bg-gradient-to-br ${purple} p-5 text-white shadow-[0_18px_40px_rgba(90,55,205,.22)] md:p-7`}>
      <div className="absolute -right-10 -top-16 h-44 w-44 rounded-full bg-white/10" /><div className="absolute -bottom-16 right-24 h-36 w-36 rounded-full bg-fuchsia-300/10" />
      <div className="relative flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-white/75">Available balance</p><p className="mt-1 text-4xl font-black tracking-tight">₹0.00</p><button onClick={()=>open("wallet")} className="mt-4 inline-flex items-center gap-1.5 rounded-full bg-white/15 px-3 py-2 text-xs font-extrabold transition hover:bg-white/25">View wallet <ChevronRight className="h-4 w-4" /></button></div><div className="grid h-24 w-24 place-items-center rounded-[28px] bg-white/12 shadow-inner"><Wallet className="h-14 w-14 text-amber-300" strokeWidth={1.6} /></div></div>
    </section>
    <div className="grid grid-cols-2 gap-3"><MiniStat label="Today’s earning" value="₹0.00" hint="Start your first task" icon={Zap} /><MiniStat label="This month" value="₹0.00" hint="Your progress" icon={TrendingUp} /></div>
    <section className="rounded-[24px] border border-violet-100 bg-white p-5 shadow-[0_10px_30px_rgba(45,28,85,.05)]">
      <div className="flex items-start justify-between gap-4"><div><span className="text-[10px] font-black tracking-[.16em] text-violet-500">TODAY’S GOAL</span><h2 className="mt-1 text-lg font-black text-[#241d34]">{watched} of 20 ads watched</h2><p className="mt-1 text-xs text-slate-500">{20-watched} ads left · Up to ₹{((20-watched)*0.8).toFixed(2)} still available</p></div><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-amber-100 text-amber-500"><Target className="h-6 w-6" /></span></div>
      <div className="mt-4 h-2.5 overflow-hidden rounded-full bg-violet-100"><div className={`h-full rounded-full bg-gradient-to-r ${purple}`} style={{width:`${Math.min(100,watched/20*100)}%`}} /></div>
      <button onClick={()=>navigate("tasks","watch")} className={`mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r ${purple} py-3 text-sm font-extrabold text-white shadow-md`}><Play className="h-4 w-4" fill="currentColor" /> Continue watching</button>
    </section>
    <section><SectionTitle title="Quick access" /><div className="grid grid-cols-3 gap-3">{shortcuts.map(({label, icon: Icon, color, action}) => <button key={label} onClick={action} className="flex min-h-28 flex-col items-center justify-center gap-3 rounded-2xl border border-[#eeebf4] bg-white p-3 text-center shadow-[0_8px_25px_rgba(30,20,60,.04)] transition hover:-translate-y-0.5 hover:shadow-md"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${color}`}><Icon className="h-6 w-6" /></span><span className="text-xs font-bold text-[#292336]">{label}</span></button>)}</div></section>
    <section><SectionTitle title="Recommended for you" side="View tasks" onSide={()=>navigate("tasks")} /><div className="overflow-hidden rounded-2xl border border-[#ece9f2] bg-white">{opportunities.map(({title,meta,reward,icon:Icon,color,action})=><button key={title} onClick={action} className="flex w-full items-center gap-3 border-b border-[#f0edf5] p-4 text-left last:border-0 hover:bg-violet-50/40"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><b className="block text-sm text-[#282133]">{title}</b><span className="text-xs text-slate-500">{meta}</span></span><span className="text-sm font-black text-violet-600">+{reward}</span><ChevronRight className="h-4 w-4 text-slate-300" /></button>)}</div></section>
    <section><SectionTitle title="Discover more" /><div className="grid gap-3 sm:grid-cols-2"><button onClick={()=>navigate("shop")} className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#fff1da] to-[#ffe1eb] p-5 text-left"><span className="text-[10px] font-black tracking-[.16em] text-orange-600">SHOP & EARN</span><b className="mt-2 block max-w-[13rem] text-lg leading-tight text-[#332234]">Compare prices and earn on every eligible order</b><span className="mt-4 inline-flex items-center gap-1 text-xs font-extrabold text-violet-700">Explore deals <ChevronRight className="h-4 w-4" /></span><ShoppingBag className="absolute -bottom-3 -right-2 h-24 w-24 rotate-[-10deg] text-orange-300/60" /></button><button onClick={()=>navigate("games")} className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#eae3ff] to-[#dff4ff] p-5 text-left"><span className="text-[10px] font-black tracking-[.16em] text-violet-600">FEATURED GAME</span><b className="mt-2 block max-w-[13rem] text-lg leading-tight text-[#29213a]">Complete the weekly challenge and unlock rewards</b><span className="mt-4 inline-flex items-center gap-1 text-xs font-extrabold text-violet-700">View challenge <ChevronRight className="h-4 w-4" /></span><Gamepad2 className="absolute -bottom-3 -right-2 h-24 w-24 rotate-[-8deg] text-violet-300/60" /></button></div></section>
    <section><SectionTitle title="Announcements" /><button onClick={()=>open("notifications")} className="flex w-full items-center gap-3 rounded-2xl border border-violet-100 bg-violet-50/60 p-4 text-left"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-violet-600 text-white"><Megaphone className="h-5 w-5" /></span><span className="min-w-0 flex-1"><b className="block text-sm text-[#282133]">Welcome to the new Glonni Ads</b><span className="mt-0.5 block text-xs leading-5 text-slate-500">Explore tasks, compare store rewards and complete game missions.</span></span><ChevronRight className="h-5 w-5 text-violet-400" /></button></section>
    <section className="rounded-2xl border border-orange-100 bg-gradient-to-r from-orange-50 to-rose-50 p-4"><div className="flex items-center gap-2 text-sm font-extrabold text-orange-700"><Flame className="h-5 w-5" fill="currentColor" /> Start your 7-day streak</div><p className="mt-1 text-xs text-slate-600">Complete one task today and keep coming back.</p><div className="mt-4 grid grid-cols-7 gap-2">{["M","T","W","T","F","S","S"].map((d,index) => <div key={`${d}${index}`} className="text-center"><span className={`mx-auto grid h-8 w-8 place-items-center rounded-full ${index === 0 ? "bg-orange-500 text-white" : "bg-white text-orange-400"}`}><Flame className="h-4 w-4" /></span><span className="mt-1 block text-[10px] font-bold text-slate-500">{d}</span></div>)}</div></section>
    <button onClick={()=>open("referral")} className={`flex w-full items-center justify-between overflow-hidden rounded-2xl bg-gradient-to-r ${purple} p-5 text-left text-white`}><span><span className="block text-lg font-extrabold">Invite friends & earn</span><span className="mt-1 block text-xs text-white/75">Get rewards when your friends start earning</span></span><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-violet-600"><ChevronRight className="h-5 w-5" /></span></button>
  </div>;
}

function TasksScreen({ active, setActive, watched, setWatched, notify }: { active: TaskKey; setActive: (v: TaskKey) => void; watched: number; setWatched: (v: number) => void; notify: (m: string) => void }) {
  const tabs: {key: TaskKey; label: string}[] = [{key:"watch",label:"Watch & Earn"},{key:"surveys",label:"Surveys"},{key:"downloads",label:"Download Apps"}];
  return <div className="space-y-5"><div className="no-scrollbar flex gap-2 overflow-x-auto pb-1">{tabs.map(t => <button key={t.key} onClick={() => setActive(t.key)} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-xs font-extrabold transition ${active === t.key ? `bg-gradient-to-r ${purple} text-white shadow-md` : "border border-[#ebe8f2] bg-white text-slate-600"}`}>{t.label}</button>)}</div>{active === "watch" && <WatchPanel watched={watched} setWatched={setWatched} notify={notify} />}{active === "surveys" && <SurveyPanel notify={notify} />}{active === "downloads" && <DownloadPanel notify={notify} />}</div>;
}

function WatchPanel({ watched, setWatched, notify }: { watched: number; setWatched: (v: number) => void; notify: (m: string) => void }) {
  const handleWatch = () => { if (watched >= 20) return notify("Daily limit reached"); setWatched(watched + 1); notify("Demo ad completed · ₹0.80 pending"); };
  return <><Hero icon={MonitorPlay} eyebrow="WATCH & EARN" title="Turn spare moments into rewards" body="Watch short sponsored videos and earn ₹0.80 for every completed ad." action="Watch now" onClick={handleWatch} />
    <section><SectionTitle title="Available ads" side={`${20-watched} remaining`} /><div className="overflow-hidden rounded-2xl border border-[#ece9f2] bg-white">{[1,2,3,4].map((n) => <button onClick={handleWatch} key={n} className="flex w-full items-center gap-3 border-b border-[#f0edf5] p-3.5 text-left last:border-0 hover:bg-violet-50/40"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-100 text-violet-600"><Play className="h-5 w-5" fill="currentColor" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold text-[#282133]">Watch video ad</span><span className="mt-0.5 flex items-center gap-1 text-xs text-slate-500"><Timer className="h-3.5 w-3.5" /> 30 seconds</span></span><span className="text-sm font-black text-violet-600">+₹0.80</span></button>)}</div></section>
    <ProgressCard current={watched} total={20} />
  </>;
}

function SurveyPanel({ notify }: { notify: (m:string)=>void }) {
  const surveys = [{title:"Shopping habits",time:"8 min",reward:"₹12",rating:5},{title:"Lifestyle & daily routine",time:"6 min",reward:"₹8",rating:4},{title:"Food & beverages",time:"10 min",reward:"₹15",rating:4},{title:"Travel preferences",time:"12 min",reward:"₹18",rating:3}];
  return <><Hero icon={ClipboardCheck} eyebrow="SHARE YOUR OPINION" title="Quick surveys, real rewards" body="Answer simple questions from trusted research partners." action="View best survey" onClick={() => notify("Survey providers will be connected later")} mint />
    <section><SectionTitle title="Available surveys" side="4 matched" /><div className="overflow-hidden rounded-2xl border border-[#ece9f2] bg-white">{surveys.map(s => <button key={s.title} onClick={() => notify("Survey providers will be connected later")} className="flex w-full items-center gap-3 border-b border-[#f0edf5] p-4 text-left last:border-0"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100 text-emerald-600"><ClipboardCheck className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold text-[#282133]">{s.title}</span><span className="mt-1 flex items-center gap-2 text-xs text-slate-500">{s.time}<span className="flex text-amber-400">{Array.from({length:s.rating}).map((_,i)=><Star key={i} className="h-3 w-3" fill="currentColor" />)}</span></span></span><span className="text-sm font-black text-emerald-600">+{s.reward}</span></button>)}</div></section>
  </>;
}

function DownloadPanel({ notify }: { notify: (m:string)=>void }) {
  const apps=[{name:"Pocket Budget",cat:"Finance",reward:"₹45",color:"bg-blue-500"},{name:"Fresh Basket",cat:"Shopping",reward:"₹28",color:"bg-emerald-500"},{name:"FitSteps",cat:"Health",reward:"₹35",color:"bg-orange-500"}];
  return <><Hero icon={Download} eyebrow="APP OFFERS" title="Discover apps and earn" body="Install, open and complete the required step to unlock rewards." action="How it works" onClick={()=>notify("Offerwall tracking will be connected later")} />
  <section><SectionTitle title="Recommended apps" side="New today" /><div className="space-y-3">{apps.map(a=><article key={a.name} className="rounded-2xl border border-[#ece9f2] bg-white p-4"><div className="flex items-center gap-3"><span className={`grid h-12 w-12 place-items-center rounded-2xl text-white ${a.color}`}><Download className="h-6 w-6" /></span><span className="min-w-0 flex-1"><b className="block text-sm text-[#282133]">{a.name}</b><span className="text-xs text-slate-500">{a.cat} · Install & register</span></span><span className="flex shrink-0 items-center gap-2"><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-black text-violet-600">Earn {a.reward}</span><button onClick={()=>notify("App offer partner will be connected later")} aria-label={`Download ${a.name}`} className="grid h-9 w-9 place-items-center rounded-full bg-[#1f1930] text-white transition hover:bg-violet-700 active:scale-95"><Download className="h-4 w-4" /></button></span></div></article>)}</div></section></>;
}

function ShopScreen({ notify, open }: { notify: (m:string)=>void; open:(detail:DetailKey)=>void }) {
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("All");
  const [selected,setSelected]=useState<string|null>(null);
  const stores=[{name:"Amazon",rate:"Up to 8%",letter:"a",color:"bg-[#fff5df] text-[#111]"},{name:"Flipkart",rate:"Up to 6%",letter:"F",color:"bg-[#fff7d6] text-blue-600"},{name:"Myntra",rate:"Up to 7%",letter:"M",color:"bg-pink-50 text-pink-600"},{name:"AJIO",rate:"Up to 5%",letter:"A",color:"bg-slate-100 text-slate-800"}];
  const products=[
    {name:"Samsung Galaxy A55 5G",category:"Mobiles",icon:"📱",subtitle:"8GB · 128GB",best:"₹24,999",earn:"₹500",offers:[{store:"Flipkart",price:"₹24,999",earning:"₹500",best:true},{store:"Amazon",price:"₹25,499",earning:"₹255",best:false},{store:"Croma",price:"₹26,199",earning:"₹393",best:false}]},
    {name:"boAt Airdopes 141",category:"Electronics",icon:"🎧",subtitle:"42-hour playback",best:"₹999",earn:"₹80",offers:[{store:"Amazon",price:"₹999",earning:"₹80",best:true},{store:"Flipkart",price:"₹1,049",earning:"₹63",best:false}]},
    {name:"Puma Running Shoes",category:"Fashion",icon:"👟",subtitle:"Men's lightweight shoes",best:"₹2,249",earn:"₹157",offers:[{store:"Myntra",price:"₹2,249",earning:"₹157",best:true},{store:"AJIO",price:"₹2,399",earning:"₹120",best:false}]},
    {name:"Whiskas Adult Cat Food",category:"Pet Care",icon:"🐾",subtitle:"Ocean fish · 3 kg",best:"₹1,099",earn:"₹66",offers:[{store:"Amazon",price:"₹1,099",earning:"₹66",best:true},{store:"Flipkart",price:"₹1,149",earning:"₹46",best:false}]},
  ];
  const categories=["All","Mobiles","Electronics","Fashion","Pet Care"];
  const visible=products.filter(p=>(category==="All"||p.category===category)&&`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  const product=products.find(p=>p.name===selected);
  if(product) return <div className="mx-auto max-w-2xl space-y-5"><button onClick={()=>setSelected(null)} className="inline-flex items-center gap-2 text-sm font-bold text-violet-600"><ArrowLeft className="h-4 w-4"/>Back to products</button><section className="rounded-[28px] border border-[#ece9f2] bg-white p-5"><div className="flex gap-4"><span className="grid h-24 w-24 shrink-0 place-items-center rounded-3xl bg-gradient-to-br from-violet-50 to-pink-50 text-5xl">{product.icon}</span><div><span className="text-[10px] font-black uppercase tracking-wider text-violet-600">{product.category}</span><h2 className="mt-1 text-xl font-black text-[#241d34]">{product.name}</h2><p className="mt-1 text-xs text-slate-500">{product.subtitle}</p><p className="mt-3 text-sm font-bold text-slate-500">Best price <span className="text-lg text-[#241d34]">{product.best}</span></p></div></div><div className="mt-5 rounded-2xl bg-emerald-50 p-4"><div className="flex items-center gap-2 text-emerald-700"><Sparkles className="h-5 w-5"/><b className="text-sm">Best earning opportunity</b></div><p className="mt-1 text-2xl font-black text-emerald-700">Earn up to {product.earn}</p><p className="mt-1 text-xs text-emerald-700/75">Estimated reward after the return period ends.</p></div></section><section><SectionTitle title="Compare store offers" side={`${product.offers.length} stores`}/><div className="space-y-3">{product.offers.map(o=><article key={o.store} className={`rounded-2xl border bg-white p-4 ${o.best?"border-emerald-300 ring-2 ring-emerald-100":"border-[#ece9f2]"}`}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 font-black text-violet-600">{o.store[0]}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><b className="text-sm">{o.store}</b>{o.best&&<span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[9px] font-black text-emerald-700">BEST VALUE</span>}</span><span className="mt-1 block text-xs text-slate-500">Price {o.price}</span></span><span className="text-right"><b className="block text-sm text-emerald-600">Earn {o.earning}</b><button onClick={()=>notify(`${o.store} affiliate link will open after integration`)} className="mt-1 inline-flex items-center gap-1 text-xs font-bold text-violet-600">Shop now<ExternalLink className="h-3 w-3"/></button></span></div></article>)}</div></section><InfoCard title="Before you shop" lines={["Always open the store through Glonni Ads","Complete the purchase in the same session","Earnings are confirmed after the return period"]}/></div>;
  return <div className="space-y-5"><Hero icon={ShoppingBag} eyebrow="SHOP & EARN" title="Compare prices. Earn more." body="Find the best store price and see your estimated earnings before you buy." action="Browse top deals" onClick={()=>document.getElementById("shop-products")?.scrollIntoView({behavior:"smooth"})} />
  <div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search products or stores" placeholder="Search products or categories" className="w-full rounded-2xl border border-[#ece9f2] bg-white py-3.5 pl-11 pr-11 text-sm outline-none focus:border-violet-400" />{query&&<button aria-label="Clear search" onClick={()=>setQuery("")} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400"><X className="h-4 w-4"/></button>}</div>
  <div className="no-scrollbar flex gap-2 overflow-x-auto">{categories.map(c=><button onClick={()=>setCategory(c)} key={c} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-xs font-bold ${category===c?"bg-[#241b38] text-white":"border border-[#ece9f2] bg-white text-slate-600"}`}>{c}</button>)}</div>
  <section><SectionTitle title="Top stores" side="View all" onSide={()=>open("stores")}/><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{stores.map(s=><button onClick={()=>notify(`${s.name} affiliate feed coming soon`)} key={s.name} className="rounded-2xl border border-[#ece9f2] bg-white p-4 text-left"><span className={`grid h-11 w-11 place-items-center rounded-xl text-xl font-black ${s.color}`}>{s.letter}</span><b className="mt-3 block text-sm text-[#282133]">{s.name}</b><span className="text-xs font-semibold text-emerald-600">{s.rate} cashback</span></button>)}</div></section>
  <section id="shop-products"><SectionTitle title="Compare & earn" side={`${visible.length} deals`}/>{visible.length?<div className="grid gap-3 md:grid-cols-2">{visible.map(p=><button key={p.name} onClick={()=>setSelected(p.name)} className="rounded-2xl border border-[#ece9f2] bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-violet-200 hover:shadow-md"><div className="flex gap-3"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-violet-50 to-pink-50 text-3xl">{p.icon}</span><span className="min-w-0 flex-1"><span className="text-[10px] font-black uppercase tracking-wider text-violet-500">{p.category}</span><b className="mt-0.5 block truncate text-sm text-[#282133]">{p.name}</b><span className="text-xs text-slate-500">{p.subtitle}</span></span></div><div className="mt-4 flex items-end justify-between border-t border-[#f0edf5] pt-3"><span><span className="block text-[10px] text-slate-400">Best price</span><b className="text-base text-[#241d34]">{p.best}</b></span><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700">Earn {p.earn}</span></div></button>)}</div>:<EmptyState icon={Search} title="No matching deals" body="Try another product name or category."/>}</section>
  <section className="rounded-2xl border border-[#ece9f2] bg-white p-5"><SectionTitle title="How it works" />{[[Store,"Choose a store","Compare cashback and prices"],[CreditCard,"Complete purchase","Shop on the partner website"],[Coins,"Earn cashback","Reward appears after confirmation"]].map(([Icon,title,body],i)=><div key={String(title)} className="flex gap-3 py-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-600"><Icon className="h-5 w-5" /></span><span><b className="block text-sm text-[#292236]">{i+1}. {String(title)}</b><span className="text-xs text-slate-500">{String(body)}</span></span></div>)}</section></div>;
}

function GamesScreen({ notify }: { notify:(m:string)=>void }) {
  const [filter,setFilter]=useState("All games");
  const [selected,setSelected]=useState<string|null>(null);
  const [query,setQuery]=useState("");
  const games=[
    {name:"Puzzle Quest",category:"Puzzle",goal:"Complete level 10",reward:"₹50",icon:"🧩",tag:"Trending",time:"25–35 min",players:"12.4K",progress:4,total:10,steps:["Install and open the game","Reach level 5 to unlock tracking","Complete level 10 within 7 days"]},
    {name:"Cricket League",category:"Sports",goal:"Win 3 matches",reward:"₹35",icon:"🏏",tag:"New",time:"15–20 min",players:"8.1K",progress:0,total:3,steps:["Install through Glonni Ads","Finish the practice match","Win 3 multiplayer matches"]},
    {name:"Word Master",category:"Word",goal:"Find 500 words",reward:"₹25",icon:"🔤",tag:"Trending",time:"20–30 min",players:"6.8K",progress:180,total:500,steps:["Open the tracked game link","Complete the tutorial","Find a total of 500 words"]},
    {name:"Ludo Club",category:"Board",goal:"Win 5 games",reward:"₹40",icon:"🎲",tag:"Top paying",time:"30–45 min",players:"15.2K",progress:2,total:5,steps:["Install and create your player ID","Play only eligible classic matches","Win 5 matches within 10 days"]},
  ];
  const visible=games.filter(g=>(filter==="All games"||g.tag===filter)&&`${g.name} ${g.goal} ${g.tag}`.toLowerCase().includes(query.toLowerCase()));
  const game=games.find(g=>g.name===selected);
  if(game) { const pct=Math.min(100,game.progress/game.total*100); return <div className="mx-auto max-w-2xl space-y-5">
    <button onClick={()=>setSelected(null)} className="inline-flex items-center gap-2 text-sm font-bold text-violet-600"><ArrowLeft className="h-4 w-4"/>Back to games</button>
    <section className={`relative overflow-hidden rounded-[28px] bg-gradient-to-br ${purple} p-6 text-white`}><div className="absolute -right-8 -top-10 text-[120px] opacity-15">{game.icon}</div><div className="relative"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-white/15 text-4xl">{game.icon}</span><span className="mt-5 inline-block rounded-full bg-white/15 px-3 py-1 text-[10px] font-black uppercase tracking-wider">{game.tag}</span><h2 className="mt-2 text-3xl font-black">{game.name}</h2><p className="mt-1 text-sm text-white/75">{game.category} game · {game.players} players</p><div className="mt-5 flex items-end justify-between"><span><span className="block text-xs text-white/70">Mission reward</span><b className="text-3xl">{game.reward}</b></span><span className="rounded-2xl bg-white px-4 py-2 text-xs font-black text-violet-700">{game.goal}</span></div></div></section>
    <section className="rounded-2xl border border-[#ece9f2] bg-white p-5"><div className="flex items-center justify-between"><div><b className="text-sm">Mission progress</b><p className="mt-1 text-xs text-slate-500">{game.progress} of {game.total} completed</p></div><span className="text-lg font-black text-violet-600">{Math.round(pct)}%</span></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-violet-100"><div className={`h-full rounded-full bg-gradient-to-r ${purple}`} style={{width:`${pct}%`}}/></div></section>
    <section><SectionTitle title="How to earn" side={game.time}/><div className="space-y-3">{game.steps.map((step,index)=><div key={step} className="flex gap-3 rounded-2xl border border-[#ece9f2] bg-white p-4"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-sm font-black ${index===0?"bg-violet-600 text-white":"bg-violet-50 text-violet-600"}`}>{index+1}</span><span><b className="block text-sm">{step}</b><span className="mt-1 block text-xs text-slate-500">Progress is verified automatically by the game partner.</span></span></div>)}</div></section>
    <InfoCard title="Important requirements" lines={["Start the game only through Glonni Ads","Use the same device until the mission is complete","New users only; reinstalling does not qualify"]}/>
    <PrimaryButton onClick={()=>notify("Game partner tracking will be connected later")}>Play game & start mission</PrimaryButton>
  </div> }
  return <div className="space-y-5"><Hero icon={Gamepad2} eyebrow="PLAY & EARN" title="Play games. Complete missions." body="Discover fun challenges and unlock rewards as you progress." action="Explore games" onClick={()=>document.getElementById("game-list")?.scrollIntoView({behavior:"smooth"})} />
  <div className="grid grid-cols-3 gap-3"><Metric label="In progress" value="3"/><Metric label="Completed" value="0"/><Metric label="Earned" value="₹0"/></div>
  <section className="rounded-2xl border border-amber-100 bg-gradient-to-r from-amber-50 to-orange-50 p-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-400 text-white"><Trophy className="h-6 w-6"/></span><span className="flex-1"><b className="block text-sm text-amber-900">Weekly game challenge</b><span className="text-xs text-amber-700">Complete 3 missions to unlock a bonus.</span></span><span className="text-sm font-black text-amber-700">0 / 3</span></div></section>
  <div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search games" placeholder="Search games or missions" className="w-full rounded-2xl border border-[#ece9f2] bg-white py-3.5 pl-11 pr-11 text-sm outline-none focus:border-violet-400"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear game search" className="absolute right-3 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-slate-100 text-slate-500"><X className="h-4 w-4"/></button>}</div>
  <div className="no-scrollbar flex gap-2 overflow-x-auto">{["All games","Trending","Top paying","New"].map(t=><button onClick={()=>setFilter(t)} key={t} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${filter===t?"bg-[#241b38] text-white":"border border-[#ece9f2] bg-white text-slate-600"}`}>{t}</button>)}</div>
  <div id="game-list" className="grid gap-3 md:grid-cols-2">{visible.map(g=><button onClick={()=>setSelected(g.name)} key={g.name} className="rounded-2xl border border-[#ece9f2] bg-white p-4 text-left transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start gap-3"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-violet-100 to-pink-100 text-3xl">{g.icon}</span><span className="min-w-0 flex-1"><span className="inline-block rounded-full bg-violet-50 px-2 py-0.5 text-[9px] font-black uppercase text-violet-600">{g.tag}</span><b className="mt-1 block text-sm text-[#282133]">{g.name}</b><span className="text-xs text-slate-500">{g.goal}</span></span><ChevronRight className="h-5 w-5 text-slate-300"/></div><div className="mt-4 flex items-center justify-between border-t border-[#f0edf5] pt-3"><span className="flex items-center gap-1 text-[11px] font-bold text-slate-500"><Timer className="h-3.5 w-3.5"/>{g.time}</span><span className="text-sm font-black text-violet-600">Earn {g.reward}</span></div></button>)}</div>
  {visible.length===0&&<EmptyState icon={Gamepad2} title="No games in this category" body="Try another filter to see available game missions."/>}</div>;
}

function ProfileScreen({ open }: { open:(detail:DetailKey)=>void }) {
  const items=[{icon:Wallet,title:"Wallet",body:"Balance and withdrawals",key:"wallet"},{icon:History,title:"Earning history",body:"All reward activity",key:"history"},{icon:Landmark,title:"UPI / Bank details",body:"Manage payout account",key:"payout"},{icon:ShieldCheck,title:"KYC verification",body:"Secure your withdrawals",key:"kyc"},{icon:CircleHelp,title:"Help & support",body:"FAQs and support tickets",key:"support"}] as const;
  return <div className="space-y-5"><section className={`rounded-[28px] bg-gradient-to-br ${purple} p-6 text-white`}><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-full bg-white/20"><CircleUserRound className="h-9 w-9" /></span><span><b className="block text-xl">Shaneel</b><span className="mt-1 flex items-center gap-1 text-xs text-white/75"><BadgeCheck className="h-4 w-4"/> Member account</span></span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-3"><span className="text-xs text-white/70">Available balance</span><b className="mt-1 block text-xl">₹0.00</b></div><div className="rounded-2xl bg-white/10 p-3"><span className="text-xs text-white/70">Minimum withdrawal</span><b className="mt-1 block text-xl">₹500</b></div></div></section>
  <div className="overflow-hidden rounded-2xl border border-[#ece9f2] bg-white">{items.map(({icon:Icon,title,body,key})=><button onClick={()=>open(key)} key={title} className="flex w-full items-center gap-3 border-b border-[#f0edf5] p-4 text-left last:border-0"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon className="h-5 w-5"/></span><span className="flex-1"><b className="block text-sm text-[#282133]">{title}</b><span className="text-xs text-slate-500">{body}</span></span><ChevronRight className="h-5 w-5 text-slate-300"/></button>)}</div>
  <div className="flex items-center gap-3 rounded-2xl bg-emerald-50 p-4 text-emerald-800"><LockKeyhole className="h-5 w-5"/><p className="text-xs leading-5"><b className="block">Your rewards stay protected</b>Secure verification will be required before withdrawal.</p></div></div>;
}

function DetailScreen({detail,open,notify}:{detail:Exclude<DetailKey,null>;open:(detail:DetailKey)=>void;notify:(message:string)=>void}) {
  if(detail==="notifications") return <DetailShell icon={Bell} title="You’re all caught up" body="Updates about rewards, tasks and withdrawals will appear here."><Notice icon={Gift} title="Welcome to Glonni Ads" body="Explore the new rewards experience." time="Today"/><Notice icon={ClipboardCheck} title="12 ads watched" body="8 more ads are available in today’s demo progress." time="Today"/><Notice icon={ShieldCheck} title="Protect your account" body="Complete KYC before your first withdrawal." time="Yesterday"/></DetailShell>;
  if(detail==="referral") return <DetailShell icon={UserRoundPlus} title="Invite friends. Earn together." body="Your referral rewards will activate when the referral system is connected."><div className={`rounded-2xl bg-gradient-to-r ${purple} p-5 text-white`}><p className="text-xs font-bold text-white/70">YOUR REFERRAL CODE</p><div className="mt-2 flex items-center justify-between rounded-xl bg-white/15 px-4 py-3"><b className="tracking-[.18em]">GLONNI-SHANEEL</b><button aria-label="Copy referral code" onClick={()=>notify("Referral code copied (demo)")}><Copy className="h-5 w-5"/></button></div></div><PrimaryButton onClick={()=>notify("Share options will be enabled with referrals")}>Share invite link</PrimaryButton><InfoCard title="How referrals work" lines={["Share your unique invite link","Friend joins and completes eligible activity","Referral reward is added after verification"]}/></DetailShell>;
  if(detail==="bonus") return <DetailShell icon={Gift} title="Daily check-in" body="Open Glonni Ads every day and complete an eligible task to build your streak."><div className="grid grid-cols-7 gap-2">{[1,2,3,4,5,6,7].map(day=><div key={day} className={`rounded-xl p-2 text-center ${day===1?"bg-orange-500 text-white":"border border-orange-100 bg-orange-50 text-orange-500"}`}><Flame className="mx-auto h-5 w-5"/><b className="mt-1 block text-xs">Day {day}</b></div>)}</div><PrimaryButton onClick={()=>notify("Today’s demo check-in is complete")}>Check in today</PrimaryButton><p className="text-center text-xs text-slate-500">Bonus values will be configured in the admin panel later.</p></DetailShell>;
  if(detail==="wallet") return <DetailShell icon={Wallet} title="₹0.00 available" body="Minimum withdrawal is ₹500.00."><div className="grid grid-cols-2 gap-3"><Metric label="Pending" value="₹0.00"/><Metric label="Lifetime earned" value="₹0.00"/></div><PrimaryButton onClick={()=>notify("A minimum ₹500 balance is required")}>Withdraw money</PrimaryButton><button onClick={()=>open("payout")} className="w-full rounded-xl border border-violet-200 py-3 text-sm font-extrabold text-violet-600">Manage payout method</button><InfoCard title="Withdrawal information" lines={["UPI and bank transfers will be supported","KYC is required before the first withdrawal","Processing status will be visible here"]}/></DetailShell>;
  if(detail==="history") return <DetailShell icon={History} title="No earnings yet" body="Your ad, survey, app, game and shopping rewards will appear here."><div className="no-scrollbar flex gap-2 overflow-x-auto">{["All","Ads","Tasks","Shopping","Withdrawals"].map((item,index)=><button key={item} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${index===0?"bg-[#241b38] text-white":"border border-[#ece9f2] bg-white text-slate-600"}`}>{item}</button>)}</div><EmptyState icon={History} title="Start earning" body="Complete your first eligible activity to create a transaction."/></DetailShell>;
  if(detail==="payout") return <DetailShell icon={Landmark} title="Add payout details" body="Choose UPI or a bank account for future withdrawals."><Field label="UPI ID" placeholder="name@bank" icon={Smartphone}/><div className="flex items-center gap-3"><span className="h-px flex-1 bg-slate-200"/><span className="text-[10px] font-bold text-slate-400">OR BANK ACCOUNT</span><span className="h-px flex-1 bg-slate-200"/></div><Field label="Account holder name" placeholder="Full name" icon={CircleUserRound}/><Field label="Account number" placeholder="Bank account number" icon={CreditCard}/><Field label="IFSC code" placeholder="e.g. SBIN0001234" icon={Landmark}/><PrimaryButton onClick={()=>notify("Details will save after secure backend connection")}>Save payout details</PrimaryButton></DetailShell>;
  if(detail==="kyc") return <DetailShell icon={ShieldCheck} title="Verify your identity" body="KYC protects your account and is required before withdrawing rewards."><Step done title="Mobile verification" body="Verified for this UI demo"/><Step title="PAN verification" body="Add and verify your PAN details"/><Step title="Identity document" body="Upload an approved document"/><Step title="Selfie check" body="Complete a secure face match"/><PrimaryButton onClick={()=>notify("Secure KYC provider will be connected later")}>Start KYC</PrimaryButton></DetailShell>;
  if(detail==="support") return <DetailShell icon={CircleHelp} title="How can we help?" body="Browse common topics or contact the support team."><div className="grid grid-cols-2 gap-3">{["Earning rewards","Task tracking","Withdrawals","Account & KYC"].map(topic=><button key={topic} onClick={()=>notify(`${topic} guide coming soon`)} className="rounded-2xl border border-[#ece9f2] bg-white p-4 text-left text-sm font-bold text-[#282133]">{topic}<ChevronRight className="mt-3 h-4 w-4 text-violet-500"/></button>)}</div><button onClick={()=>notify("Support tickets will be enabled with the backend")} className="flex w-full items-center gap-3 rounded-2xl border border-[#ece9f2] bg-white p-4 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 text-violet-600"><Mail className="h-5 w-5"/></span><span><b className="block text-sm">Create support ticket</b><span className="text-xs text-slate-500">We’ll show replies inside the app</span></span></button></DetailShell>;
  return <StoreDirectory notify={notify}/>;
}

function StoreDirectory({ notify }: { notify: (message: string) => void }) {
  const [query, setQuery] = useState("");
  const stores=["Amazon","Flipkart","Myntra","AJIO","Croma","Tata CLiQ","Nykaa","Reliance Digital"];
  const visible=stores.filter(store=>store.toLowerCase().includes(query.toLowerCase()));
  return <DetailShell icon={Store} title="Compare partner stores" body="Affiliate rates and product comparison will update after provider integration."><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search stores" aria-label="Search partner stores" className="w-full rounded-2xl border border-[#ece9f2] bg-white py-3.5 pl-11 pr-11 text-sm outline-none focus:border-violet-400"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear store search" className="absolute right-3 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-full bg-slate-100 text-slate-500"><X className="h-4 w-4"/></button>}</div><div className="grid grid-cols-2 gap-3">{visible.map(store=><button key={store} onClick={()=>notify(`${store} integration coming soon`)} className="rounded-2xl border border-[#ece9f2] bg-white p-4 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 font-black text-violet-600">{store[0]}</span><b className="mt-3 block text-sm">{store}</b><span className="text-xs text-emerald-600">Rates coming soon</span></button>)}</div>{visible.length===0&&<EmptyState icon={Store} title="Store not found" body="Try another store name or clear your search."/>}</DetailShell>;
}

function DetailShell({icon:Icon,title,body,children}:{icon:LucideIcon;title:string;body:string;children:React.ReactNode}) { return <div className="mx-auto max-w-2xl space-y-5"><section className="rounded-[26px] border border-violet-100 bg-gradient-to-br from-violet-50 to-white p-5"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-600 text-white"><Icon className="h-6 w-6"/></span><h2 className="mt-4 text-2xl font-black text-[#241d34]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p></section>{children}</div> }
function Notice({icon:Icon,title,body,time}:{icon:LucideIcon;title:string;body:string;time:string}) { return <article className="flex gap-3 rounded-2xl border border-[#ece9f2] bg-white p-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon className="h-5 w-5"/></span><span className="flex-1"><b className="block text-sm">{title}</b><span className="mt-1 block text-xs leading-5 text-slate-500">{body}</span></span><span className="text-[10px] text-slate-400">{time}</span></article> }
function PrimaryButton({onClick,children}:{onClick:()=>void;children:React.ReactNode}) { return <button onClick={onClick} className={`w-full rounded-xl bg-gradient-to-r ${purple} py-3.5 text-sm font-extrabold text-white shadow-md`}>{children}</button> }
function InfoCard({title,lines}:{title:string;lines:string[]}) { return <section className="rounded-2xl border border-[#ece9f2] bg-white p-5"><b className="text-sm">{title}</b><div className="mt-3 space-y-3">{lines.map(line=><div key={line} className="flex gap-2 text-xs leading-5 text-slate-500"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500"/>{line}</div>)}</div></section> }
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-2xl border border-[#ece9f2] bg-white p-4"><span className="text-xs text-slate-500">{label}</span><b className="mt-1 block text-xl">{value}</b></div> }
function EmptyState({icon:Icon,title,body}:{icon:LucideIcon;title:string;body:string}) { return <div className="rounded-2xl border border-dashed border-violet-200 bg-white p-8 text-center"><Icon className="mx-auto h-9 w-9 text-violet-400"/><b className="mt-3 block text-sm">{title}</b><p className="mx-auto mt-1 max-w-xs text-xs leading-5 text-slate-500">{body}</p></div> }
function Field({label,placeholder,icon:Icon}:{label:string;placeholder:string;icon:LucideIcon}) { return <label className="block text-xs font-bold text-slate-600">{label}<span className="relative mt-2 block"><Icon className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input placeholder={placeholder} className="w-full rounded-xl border border-[#e8e4ef] bg-white py-3 pl-11 pr-4 text-sm font-normal outline-none focus:border-violet-400"/></span></label> }
function Step({title,body,done=false}:{title:string;body:string;done?:boolean}) { return <div className="flex gap-3 rounded-2xl border border-[#ece9f2] bg-white p-4"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${done?"bg-emerald-100 text-emerald-600":"bg-slate-100 text-slate-400"}`}>{done?<CheckCircle2 className="h-5 w-5"/>:<ShieldCheck className="h-4 w-4"/>}</span><span><b className="block text-sm">{title}</b><span className="text-xs text-slate-500">{body}</span></span></div> }

function Hero({ icon: Icon, eyebrow, title, body, action, onClick, mint=false }: {icon:LucideIcon;eyebrow:string;title:string;body:string;action:string;onClick:()=>void;mint?:boolean}) { return <section className={`relative overflow-hidden rounded-[26px] ${mint ? "bg-gradient-to-br from-[#36c6a0] to-[#189f83]" : `bg-gradient-to-br ${purple}`} p-5 text-white shadow-[0_18px_38px_rgba(90,55,205,.18)] md:p-7`}><div className="absolute -right-8 -top-8 h-36 w-36 rounded-full bg-white/10"/><div className="relative flex items-center justify-between gap-4"><div className="max-w-md"><span className="text-[10px] font-black tracking-[.2em] text-white/70">{eyebrow}</span><h2 className="mt-2 text-2xl font-black leading-tight">{title}</h2><p className="mt-2 text-sm leading-6 text-white/80">{body}</p><button onClick={onClick} className="mt-4 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-xs font-extrabold text-violet-700 shadow-sm">{action}<ChevronRight className="h-4 w-4"/></button></div><span className="hidden h-28 w-28 shrink-0 place-items-center rounded-[30px] bg-white/15 sm:grid"><Icon className="h-16 w-16" strokeWidth={1.5}/></span></div></section> }

function MiniStat({label,value,hint,icon:Icon}:{label:string;value:string;hint:string;icon:LucideIcon}) { return <div className="rounded-2xl border border-[#eeebf4] bg-white p-4 shadow-[0_8px_25px_rgba(30,20,60,.04)]"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{label}</span><Icon className="h-4 w-4 text-violet-500"/></div><b className="mt-2 block text-xl text-[#211a31]">{value}</b><span className="text-[10px] text-slate-400">{hint}</span></div> }
function SectionTitle({title,side,onSide}:{title:string;side?:string;onSide?:()=>void}) { return <div className="mb-3 flex items-center justify-between"><h3 className="text-base font-extrabold text-[#241e30]">{title}</h3>{side&&(onSide?<button onClick={onSide} className="text-xs font-bold text-violet-600">{side}</button>:<span className="text-xs font-bold text-violet-600">{side}</span>)}</div> }
function ProgressCard({current,total}:{current:number;total:number}) { const pct=Math.min(100,current/total*100); return <section className="rounded-2xl border border-[#ece9f2] bg-white p-4"><div className="flex items-center justify-between"><div><b className="text-sm text-[#292236]">Daily reward progress</b><p className="mt-1 text-xs text-slate-500">Complete {total} ads to finish today’s goal</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-100 text-amber-500"><Target className="h-5 w-5"/></span></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-violet-100"><div className={`h-full rounded-full bg-gradient-to-r ${purple} transition-all`} style={{width:`${pct}%`}}/></div><div className="mt-2 flex justify-between text-xs font-bold"><span className="text-violet-600">{current} completed</span><span className="text-slate-400">{total} total</span></div></section> }
function BottomNav({active,navigate}:{active:NavKey;navigate:(key:NavKey)=>void}) { return <nav className="fixed inset-x-0 bottom-0 z-40 mx-auto max-w-[1180px] border-t border-[#ebe8f1] bg-white/95 px-2 pb-[max(.65rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur-xl md:bottom-5 md:rounded-b-[32px]"><div className="grid grid-cols-5">{navItems.map(({key,label,icon:Icon})=><button key={key} onClick={()=>navigate(key)} className={`relative flex min-h-14 flex-col items-center justify-center gap-1 rounded-2xl text-[10px] font-bold transition ${active===key?"text-violet-600":"text-slate-500 hover:text-violet-500"}`}>{active===key&&<span className="absolute top-0 h-1 w-6 rounded-full bg-violet-600"/>}<Icon className="h-5 w-5" strokeWidth={active===key?2.7:2}/><span>{label}</span></button>)}</div></nav> }
